### ISSUE TITLE
A couple of minor changes.

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#10]
Hi, I'd like to make two changes:

Can DeltaBot distinguish all of its comments please? If you've not encountered distinguishing before, basically it's a moderator action that makes a mod's username green and adds an [M] beside it. 

Can we remove this from all of DeltaBot's comments:

[[Wiki](http://www.reddit.com/r/changemyview/wiki/deltabot)][[Code](https://github.com/MystK/delta-bot-three/)][/r/DeltaBot3]

and replace it with this:

[[The Delta System Explained](https://www.reddit.com/r/changemyview/wiki/deltasystem)]

**Comment by Snorrrlax** [comment]
Also, if it's not too much hassle could we change the sentence at the top of user wiki pages from "has received x delta(s)" to "has received x deltas", and when a user receives their first delta: "has received 1 delta"?

**Comment by MystK** [comment]
Hey Snorrrlax, will do. Could you please split this up into three issues so I can track progress? After I will close this one.

**Comment by Snorrrlax** [comment]
Thanks. Done :)
