### ISSUE TITLE
All issues without the "in progress" label are free to be worked on

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#100]
I've just removed all "help wanted" labels, as they were only attached to a few issues and I believe this may have caused some confusion. 

**Anybody is welcome to work on any issue that ~~is unassigned~~ doesn't have an "in progress" label**, i.e. assume all issues have "help wanted" attached to them, unless somebody is already working on it (although you are still welcome to give your thoughts on the issue in this case). 

To save two people working on an issue unknowingly at the same time, **it would be a good idea to ~~assign yourself to one~~ leave a comment on the issue if you're taking it on.**

**Edits:** As per the discussion below, I'm now aware that not everybody can assign themselves. Please leave a comment instead and I'll add the "in progress" label.

Thanks!

**Comment by roastchicken** [comment]
How do we assign ourselves to an issue? I'm pretty sure only the repository managers (or whatever they're called) have the ability to assign people.

**Comment by Snorrrlax** [comment]
Ah I didnt realise. In that case just leave the comment on the issue and I'll either assign you (if I can) or make an edit at the top of the post to make people aware.

**Comment by Snorrrlax** [comment]
Perhaps @MystK can clarify if there's a way to allow this or not?

**Comment by roastchicken** [comment]
Per @MystK's [comment](https://github.com/MystK/delta-bot-three/issues/50#issuecomment-267826652), should people be assigned or should they just comment saying "hey I'm working on this"?

**Comment by MystK** [comment]
No, you can't assign someone not a core contributor to the project. You can just mention that you're working on it. We don't have enough developers that this process would be a problem yet, so I think it's fine.

**Comment by Snorrrlax** [comment]
The reason I brought this up is because I messaged a few people on reddit, who said they would take a look. A couple asked about which issues so I realised there may be some confusion/people working on the same issues.

**Comment by Snorrrlax** [comment]
@stedop @ansballard @CrazyPython @sahuk @Beasta @giodamelio @JayFTW @nathandial @TheJaySmith

Hi everyone. I'm pinging those who previously expressed interest in, contributed to, or forked DeltaBot's code (minus those who I've heard from recently).

Are any of you interested in taking on an issue? It would be a great help!

**Comment by Snorrrlax** [comment]
@stedop @ansballard @CrazyPython @sahuk @Beasta @giodamelio @JayFTW @nathandial @TheJaySmith @AHarman @Pluckerpluck 

Hi everyone. I'm pinging those who previously expressed interest in, contributed to, or forked DeltaBot's code (minus those who I've heard from recently).

Are any of you interested in taking on an issue? It would be a great help!
