### ISSUE TITLE
The weekly deltaboard isn't updating 

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#107]
There have been deltas added to the daily deltaboard, but not the weekly one.

**Comment by Snorrrlax** [comment]
The weekly deltaboard has now been populated, just as the daily one was wiped at midnight UTC: https://www.reddit.com/r/changemyview/wiki/deltaboards?v=ac59fd50-d147-11e6-8bd6-0e7ec5148336

Not sure what's going on there.

**Comment by MystK** [comment]
Weird indeed. Is this still happening?

**Comment by Snorrrlax** [comment]
I won't know for sure until a new week starts, but I'd assume so.

**Comment by Snorrrlax** [comment]
Yes, definitely still happening. The weekly deltaboard has been refreshed but is not updating, even though there are deltas on the daily deltaboard. It seems that the weekly deltaboard rightly refreshes on Monday, but doesn't start updating until Tuesday.

**Comment by Snorrrlax** [comment]
Happened again today.
