### ISSUE TITLE
Workaround for missing deltas failed.

### ISSUE THREAD

**Issue by hacksoncode** [MystK/delta-bot-three#109]
I thought I had correctly "fixed" [this user's wiki page](https://www.reddit.com/r/changemyview/wiki/user/im_screaming) by adding manual delta entries, but they just were awarded a new delta and the bot kind of scrambled their page and removed the manual deltas.

What did I do wrong? Here's the [history of the page where I tried to fix it](https://www.reddit.com/r/changemyview/wiki/user/im_screaming?v=7f8404d0-c6d7-11e6-9d75-12b0f8606fcc). 

We really need some way to deal with this more effectively/efficiently. I'm worried that when the bot is changed, this problem will reoccur. Perhaps a message that can be sent (only be a mod) that will cause the bot to add the manual deltas in whatever format it wants to see?

**Comment by MystK** [comment]
I will use this issue to document how to add a delta, then could you open up another issue to implement "Add Deltas To Wiki from Message" or something like that? Thoughts, @Snorrrlax?

**Comment by Snorrrlax** [comment]
I'm not sure what you mean?

**Comment by sxlijin** [comment]
> Perhaps a message that can be sent (only be a mod) that will cause the bot to add the manual deltas in whatever format it wants to see?

There should probably be some way to automate this, instead of requiring a human to generate the message. XSS protections will make it slightly harder, but you could always just have something that generates a message to do X, and then just let someone copy-paste it in a delta bot PM.

**Comment by hacksoncode** [comment]
Thanks MystK. Yeah, I believe I followed the instructions on another one of the bugs about missing deltas, but it seems I did something wrong, so fresh documentation would be helpful.

**Comment by Snorrrlax** [comment]
@MystK I think this can be closed for now, but documentation seems it would be useful at some point.
