### ISSUE TITLE
Improve documentation (and maybe incorporate Flow?)

### ISSUE THREAD

**Issue by wesm87** [MystK/delta-bot-three#114]
It seems like the inline documentation is pretty lacking, which makes it somewhat difficult for people who are unfamiliar with the code to jump in and make contributions. I'd be willing to go through and add JSDoc comments (and, ideally, Flow type declarations).

**Comment by MystK** [comment]
Yes, that would be great if you could make a PR for this. ;)

**Comment by wesm87** [comment]
@MystK ok great, where would be the best place to ask questions so I can make sure I'm documenting things accurately? Is there a Slack channel or Gitter community or something?

**Comment by MystK** [comment]
Yes, there is a slack. :) @Snorrrlax would be able to invite you I believe.

**Comment by Snorrrlax** [comment]
@wesm87 I can add you to our slack channel if you provide your email address. You can PM it to me on reddit if you'd prefer not to include it in a comment here.

**Comment by MystK** [comment]
Going to closed this as it is stale. A PR is welcome to add more comments! :)
