### ISSUE TITLE
DeltaBot & Ampersand

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#117]
It seems to me that DeltaBot has a problem with '**&**'. Every time DeltaBot updates an area that contains one, **amp;** is added, leading to something like:

> **&amp;amp;amp;amp;amp;amp;amp;**

One example was the [sidebar bug](https://github.com/MystK/delta-bot-three/issues/95), where the ampersand in the sidebar (which is there for CSS purposes, I think) would have amp; added every time DeltaBot updated the monthly deltaboard.

Similarly with the [wiki page bug](https://github.com/MystK/delta-bot-three/issues/58), it seems that whenever a post entry contained '&' in the title, DeltaBot would add amp; every time the page was updated. [Here's](https://www.reddit.com/r/changemyview/wiki/user/crayshack) an example (the entry I'm referring to has the date 3/6/2016).

Most recently, as I mentioned in [this comment](https://github.com/MystK/delta-bot-three/pull/105#issuecomment-270374896), the quote symbol in DeltaLog entries went from '>' to &amp;gt; to &amp;amp;gt; and so on.

Rather than treat each of these issues separately, should we aim to stop this happening in *any* possible scenario?

**Comment by MystK** [comment]
It's a hard issue to fix in all scenarios because it has to do with the way Reddit returns the data. When we use the &, and some other characters, when we get the data from Reddit, Reddit adds the `amp;` to it. I think we can pass the data we receive from Reddit through a decoder which removes it, but it only happens when retrieving certain parts of Reddit. I don't know a good solution ATM, but hopefully others know more about this topic.

**Comment by MystK** [comment]
It looks like I implemented code to handle this already in `src\get-wiki-content.js`. I just need to apply the code to places of concern(such as the side bar)

**Comment by Snorrrlax** [comment]
I'm assuming post titles that contain '&' might also cause problems in a DeltaLog post's hidden params?

**Comment by MystK** [comment]
I added the code to where we parse hidden parameters. This might cause bugs but this specific issue is most likely fixed almost everywhere. Will keep this open for now.

**Comment by Snorrrlax** [comment]
Another case: #135

**Comment by MystK** [comment]
Any other instances of this happening?

**Comment by Snorrrlax** [comment]
I think I've covered everything above

**Comment by Snorrrlax** [comment]
Will reopen if anything else comes up.
