### ISSUE TITLE
Move deployment from Codeship to TravisCI

### ISSUE THREAD

**Issue by MystK** [MystK/delta-bot-three#123]
Codeship is slow and is UI driven. This leaves room for errors. TravisCI has parallel builds and is free for open source projects.

**Comment by dennisnewel** [comment]
What are the issues with Codeship? it's free for open source projects as well so i'm sure there's something we can do to fix the problems?

**Comment by MystK** [comment]
Codeship free allows only 1 thread. Travis CI free allows multiple threads, so it's much faster. Only way I can think of "fixing" Codeship is to pay for it. Thoughts?

**Comment by dennisnewel** [comment]
We'd be happy to give you more resources. 

Unfortunately our internal systems won't let me automatically upgrade open source projects, so it'd have to be manual for now. We've found your account and have upgraded it to 5 parallel builds and 5 testing pipelines; that should hopefully help you make your builds faster.

Let me know if you need any other help regarding Codeship :)

**Comment by MystK** [comment]
Wow, that's great! Thank you so much! If everything works out, I will migrate everything from Travis CI to Codeship instead! :)))

**Comment by dennisnewel** [comment]
Happy to help out! it's not clearly enough stated on the site yet (partly because it's still a manual process) but we're definitely up for given more resources to OSS projects; it's good to give something back to the community

**Comment by MystK** [comment]
Hi @dennisnewel, just wanted to say thanks again! It's as quick as I had hoped for! Will be ditching Travis CI and keeping Codeship! 👍
