### ISSUE TITLE
Remaining DeltaLog and Stickied Comment Issues

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#124]
Thanks very much for releasing DeltaLog and stickied comments!

When someone has time, there are still a few things remaining:

* I just tried to test usernames with underscores [here](https://www.reddit.com/r/changemyviewDB3Dev/comments/5lywmf/cmv_this_is_a_deltalog_test/dc6z83p/?context=3), but the delta wasn't added to the /r/DeltaLogDB3Dev post? 

* The change suggested in [this comment](https://github.com/MystK/delta-bot-three/pull/105#issuecomment-270011435):

> In the event of a comment earning more than one delta, it would be good to compile it in the DeltaLog post like so:
>
>* 3 deltas from /u/user1, /u/user2 and /u/user3 to /u/recipient for "This is the 200 character truncated comment..."
>
>* 2 deltas from /u/user1 and /u/user2 to /u/recipient for "This is the 200 character truncated comment..."
>
>* 4 deltas from /u/user1, /u/user2, /u/user3 and /u/user4 to /u/recipient for "This is the 200 character truncated comment..."

* As mentioned in [this comment](https://github.com/MystK/delta-bot-three/pull/105#issuecomment-270126234):

> The stickied comment is supposed to say "OP has awarded N deltas", whereas right now it says "OP has awarded at least one delta"

I think that's it!

**Comment by MystK** [comment]
![image](https://cloud.githubusercontent.com/assets/7399140/21774837/a833d4f2-d648-11e6-9194-d76f6b2dcf52.png)

Here is the error happening

**Comment by MystK** [comment]
This is due to the length of the post, not the underscore. The POST query in 487 needs to be changed from a URL query to a body

**Comment by MystK** [comment]
closing to split it up
