### ISSUE TITLE
DeltaLog Post Bug

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#125]
There seems to be a bug in the "other users" section of this post: 

https://www.reddit.com/r/DeltaLog/comments/5my4vw/deltas_awarded_in_cmv_human_rights_are_a/

**Comment by MystK** [comment]
That's the hidden parameters being shown. Just needs to be hidden.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by Snorrrlax** [comment]
Just found it odd since the other posts don't have this problem?

**Comment by MystK** [comment]
It has to do with the content of the post. I think a certain character and such.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
