### ISSUE TITLE
Quotes in DeltaLog posts

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#126]
I just noticed something in [this](https://www.reddit.com/r/DeltaLog/comments/5mysys/deltas_awarded_in_cmv_the_internet_is_more/) /r/DeltaLog post. The truncated text misses out the first non-quoted sentence of [this comment](https://www.reddit.com/r/changemyview/comments/5mur2m/cmv_the_internet_is_more_detrimental_to_society/dc6p2hc/):

>>Yes, but a bully on the internet can be and usually is anonymous which is why it's easier to bully online vs IRL.
>
>And it's vastly easier to ignore the bullying. Would you rather be cyber bullied or physically assaulted?
>
>>but how much difference is there really all together.
>
>It's the difference between having access to billions of diverse opinions regardless of who you are or where you live vs a few hundred similar-ish ones if you're really well connected in a large city.

It became:

"[It's the difference between having access to billions of diverse opinions regardless of who you are or where you live vs a few hundred similar-ish ones if you're really well connected in a large cit...](https://www.reddit.com/r/changemyview/comments/5mur2m/cmv_the_internet_is_more_detrimental_to_society/dc6p2hc/)"

When this would be better: 

"[**[Quote]** And it's vastly easier to ignore the bullying. Would you rather be cyber bullied or physically assaulted? **[Quote]** It's the difference between having access to billions of diverse opinions regardless of who yo...](https://www.reddit.com/r/changemyview/comments/5mur2m/cmv_the_internet_is_more_detrimental_to_society/dc6p2hc/)"

Using **[Quote]** in place of all reddit quotes would be great. If this could somehow be exempt from the 200 character count that would be even better.

**Comment by Snorrrlax** [comment]
[This comment](https://www.reddit.com/r/changemyview/comments/5mxzx3/cmv_human_rights_are_a_dangerous_concept_that/dc7afmm/) shows the problem even better. It was added to [this DeltaLog post](https://www.reddit.com/r/DeltaLog/comments/5my4vw/deltas_awarded_in_cmv_human_rights_are_a/), and only the very last sentence of it was copied over:

"[Note that my robbing you creates some very minor obligations on third parties. They have an obligation to avoid buying my stolen Swiss chocolate, sure. They don't have an obligation to do "literally...](https://www.reddit.com/r/changemyview/comments/5mxzx3/cmv_human_rights_are_a_dangerous_concept_that/dc7afmm/)"

**Comment by MystK** [comment]
The issue here is that the regular expression I used is greedy. We need to convert the regular expression to not be greedy and also make it check for multiple quotes(if it doesn't do it)

**Comment by Snorrrlax** [comment]
Strange, this one didn't work: https://www.reddit.com/r/DeltaLog/comments/5ptrj7/deltas_awarded_in_cmv_i_would_be_happier_under/
