### ISSUE TITLE
delta log combine comments

### ISSUE THREAD

**Issue by MystK** [MystK/delta-bot-three#128]
The change suggested in this comment:

In the event of a comment earning more than one delta, it would be good to compile it in the DeltaLog post like so:

3 deltas from /u/user1, /u/user2 and /u/user3 to /u/recipient for "This is the 200 character truncated comment..."

2 deltas from /u/user1 and /u/user2 to /u/recipient for "This is the 200 character truncated comment..."

4 deltas from /u/user1, /u/user2, /u/user3 and /u/user4 to /u/recipient for "This is the 200 character truncated comment..."

splitting up #124

**Comment by Snorrrlax** [comment]
Can this be closed?

**Comment by wyantb** [comment]
Yeah, this is what my PR did.  Closing.  I'm assuming if there were major issues with this piece you'd have filed separate tickets anyway.
