### ISSUE TITLE
delta log i18n change

### ISSUE THREAD

**Issue by MystK** [MystK/delta-bot-three#129]
As mentioned in this comment:
The stickied comment is supposed to say "OP has awarded N deltas", whereas right now it says "OP has awarded at least one delta"

splitting up #124

**Comment by MystK** [comment]
To add info to this, it's kind of hard because it requires figuring out how many deltas have been awarded by OP, and that info requires fiddling around with the code and maybe making another API call.

**Comment by wyantb** [comment]
It would require a bit of restructuring, I think, but not another api call; if `findOrMakeDeltaLogPost` returned the hidden params on the delta log post itself in addition to it's current return, `findOrMakeStickiedComment` would be able to use the list of comments in those params to decide what to do - nothing, update the comment, or make the comment.
