### ISSUE TITLE
DeltaLog text bug

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#131]
[Here's](https://www.reddit.com/r/DeltaLog/comments/5n2lba/deltas_awarded_in_cmv_body_positivity_is/) the problem post.

The third entry reads "[No they don't. Smokers and overweight people might have higher healthcare costs while they're alive, but they tend to die younger (60s and 70s&paren&&& and thus don't draw on social security and Medicare for...](https://www.reddit.com/r/changemyview/comments/5n24dv/cmv_body_positivity_is_generally_an_excuse_for/dc860dj/)"

When it should say "[No they don't. Smokers and overweight people might have higher healthcare costs while they're alive, but they tend to die younger (60s and 70s) and thus don't draw on social security and Medicare for...](https://www.reddit.com/r/changemyview/comments/5n24dv/cmv_body_positivity_is_generally_an_excuse_for/dc860dj/)"

**Comment by Snorrrlax** [comment]
It's progressed into something even worse: 

"No they don't. Smokers and overweight people might have higher healthcare costs while they're alive, but they tend to die younger (60s and 70s&amp;amp;paren&amp;amp;&amp;amp;&amp;amp; and thus don't draw on social security and Medicare for..."

**Comment by MystK** [comment]
Should be fixed
