### ISSUE TITLE
Links in DeltaLog text

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#132]
[This post](https://www.reddit.com/r/DeltaLog/comments/5n9q3k/deltas_awarded_in_cmv_liberalism_is_superior_to/) has a messed up link:

1 delta from OP to /u/GnosticGnome for "[How about Paul Ryan's anti-poverty plan](http://www.speaker.gov/press-release/republicans-unveil-better-way-fight-poverty)? His goals and justifications there seem to be focused on measurable impact ...](https://www.reddit.com/r/changemyview/comments/5n9505/cmv_liberalism_is_superior_to_conservatism/dc9ozu6)"

The first part of the sentence [links to speaker.gov](http://www.speaker.gov/press-release/republicans-unveil-better-way-fight-poverty), but I thought links were supposed to be ignored when copying text over?

Does [this change](https://github.com/MystK/delta-bot-three/pull/105/commits/479f72d6615a69b99d2e272cc0fbda30d20a6d36#diff-1fdf421c05c1140f6d71444ea2b27638L385) have anything to do with it?

**Comment by MystK** [comment]
https://github.com/MystK/delta-bot-three/blob/master/src/index.js#L386

The line above should be the one converting the links. I am not sure what's wrong and would have to investigate. In the meantime we can manually fix the text no problem.

**Comment by Snorrrlax** [comment]
I'll list any other cases in this comment section.

Here's some:

https://www.reddit.com/r/DeltaLog/comments/5nwuh9/deltas_awarded_in_cmv_bernie_sanders_could_have/

https://www.reddit.com/r/DeltaLog/comments/5nnz2p/deltas_awarded_in_cmv_comcast_verizon_and_atampts/ (I made a separate issue for this one since the title contains &amp;)

**Comment by Snorrrlax** [comment]
https://www.reddit.com/r/DeltaLog/comments/5o1jdu/deltas_awarded_in_cmv_no_one_is_actually_happy/

**Comment by Snorrrlax** [comment]
https://www.reddit.com/r/DeltaLog/comments/5of2ou/deltas_awarded_in_cmv_the_stock_market_is_a_scam/

**Comment by Snorrrlax** [comment]
I've stopped looking out for these but I think I've probably provided enough examples to find a common link that may be causing this bug.

**Comment by Snorrrlax** [comment]
In [this case](https://www.reddit.com/r/DeltaLog/comments/5r5q3m/deltas_awarded_in_cmv_i_support_donald_trump/) "[Quote]" is unlinked, presumably something to do with the first word of the comment being a link.

**Comment by Snorrrlax** [comment]
@wyantb Any idea what's happening here?

**Comment by wyantb** [comment]
Not sure offhand, no, but the truncation methods are all unit-testable and I can try to find some time to look at it (later today/Friday/Saturday?) since it looks like this happens enough to be worth fixing.

**Comment by Snorrrlax** [comment]
That would be great, thank you!
