### ISSUE TITLE
Edits within 3 minutes of commenting

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#139]
MystK has almost finished working on edited comments, which is great news! This is a large step towards a watertight delta system. 

There does remain an issue however, and that is the 3 minutes between a comment being submitted and becoming 'edited'.

If you edit a comment within the first three minutes, it won't be considered an edited comment (there'll be no asterisk next to it). This means DeltaBot has scanned it, found no delta, and since the comment isn't added to [the edited list](https://www.reddit.com/r/changemyview/about/edited.json) to be rescanned, it'll be missed. 

Here's the relevant line from reddit's code: https://github.com/reddit/reddit/blob/master/r2/r2/controllers/api.py#L2005 (The asterisk also appears if the comment has more than 2 upvotes and is edited within 3 minutes).

This might not sound like a big issue, but we do receive missed delta messages from time to time where the delta comment doesn't appear to be edited (no asterisk). But since we assume that DB3 is perfectly functional for non-edited delta comments, the delta must've been added within three minutes in these cases.

It makes sense though. A lot of people re-read their comment after submitting it only to realise they've forgotten something, and quickly edit it in.

Any ideas on how to handle this?

**Comment by hacksoncode** [comment]
About the only "solution" that I can think of would be to queue comments and only process them 3 minutes after they are posted.

So every time a comment is added, add the comment ID to the queue along with the time, and then process all entries at the head of the queue that were posted >3 minutes ago (or maybe 200 seconds, to be safe). 

I suppose in order to protect against periods of time with few comments, that could be augmented by a 3 minute "watchdog timer" that is reset on each comment, and triggers processing if it ever goes off.

**Comment by MystK** [comment]
I agree with @hacksoncode and think that that is the only solution unless someone has a better solution

**Comment by Snorrrlax** [comment]
Would this variation of that solution work?:

When a new comment comes in, scan it. If there's a delta, proceed as the current code does. If no delta, store the comment ID and check three minutes later, at which point if there's still no delta this data can be discarded, since any further edits will be checked again anyway.

**Comment by hacksoncode** [comment]
That would award deltas a little bit faster, but it has the downside of not catching it if OP changes their mind within 3 minutes and edits out their delta or removes their comment. 

Since reddit doesn't let you see those "stealth edits", I'm pretty sure the only way to do this reliably is to delay awarding all deltas for 3 minutes. 

That doesn't seem like a big deal, though.

**Comment by MystK** [comment]
Thinking about it, I think it would be much more robust if it didn't keep any state at all, even if only for 3 minutes.

I think every 30 seconds, I will check delta comments older than 4 minutes. Once I reach a delta comment that deltabot has replied to, I will stop. This is on top of the current running processes.

Thoughts?

**Comment by Snorrrlax** [comment]
@hacksoncode but isn't that a downside we already have? DeltaBot doesn't check for removed deltas?

**Comment by hacksoncode** [comment]
@Snorrrlax: Technically yes, but it would seem better to have an architecture that doesn't have to change when we actually *do* support checking for removed deltas. 

@MystK: Yeah, maintaining state is problematic. If you are capable of checking comments by time that seems like a fine approach, though it does mean processing a lot of comments repetitively if you go all the way back to the last awarded delta/error. I suppose that's not the end of the world, though. 

I guess we don't have any limit on total CPU usage, though we do have a (fairly generous) limit on bandwidth.

**Comment by Snorrrlax** [comment]
I don't have any evidence, but my gut feeling is that edits to remove deltas are very rare, especially within 3 minutes of commenting. Why not just rely on user reports and the delete command for this?

**Comment by hacksoncode** [comment]
It's a good point that removed deltas are rare, but MystK's point about state is also a very good one. The "check again in 3 minutes" approach has the problem that if DB crashes or is restarted (I think that happens often enough to be a worry, but I'm not sure we have statistics), the saved state of "I need to check these comments again" would be lost. 

Whereas checking only comments that are 4+ minutes old when DB wakes up (until reaching one DB can verify it has processed) will always catch every instance of a 3-minute-edited delta comment.

My biggest worry about that is that it could have scaling issues if we ever run into a situation where there are no deltas for a long while. Let's say for whatever reason we had no deltas for a day or two (not saying this is likely), then every 30 seconds DB would be scanning a couple days worth of comments. 

I'm wondering if there's *some* kind of "I've processed up to this time" marker that DB could store regularly to avoid that... yes, it's state, but so are the user wikis. Maybe an hourly watchdog?

**Comment by Snorrrlax** [comment]
How often does DeltaBot scan new comments? Is it consistent?

**Comment by MystK** [comment]
@hacksoncode has good points. If state isn't kept, we would have to check a lot of comments. If we are using snoowrap(I am testing it out), it might handle the Reddit API limits for us.

At the moment we check every 30 seconds. A state IS saved, but in the hard drive in case of crashes. I'd like to move away from that.

**Comment by Snorrrlax** [comment]
Would it be possible to scan every comment that is between 0 and 4 minutes old, every time? It would be like DeltaBot is watching each comment until it's old enough to have an asterisk if edited. Apologies if I'm missing something.

**Comment by hacksoncode** [comment]
The issue with doing that is if DB goes down even fairly briefly, and a comment is edited during that time (but before the 3 minute limit), we wouldn't catch it. 

Scanning back to a "known good point" (whether that's the last awarded comment or some reasonable time threshold set as a "watchdog timer") is the only way to avoid that.

**Comment by Snorrrlax** [comment]
Ah I see what you're saying.

I'm not really opposed to the methods suggested above, I'm just trying to figure out if there's a way for DeltaBot to continue awarding deltas near-instantaneously.

**Comment by Snorrrlax** [comment]
And of course, if that's not possible, I'd certainly rather deltas were awarded a few minutes later than have some be missed.

**Comment by MystK** [comment]
I think we can have the best of both worlds by having two queues running. One scanning ALL NEW comments every 30 seconds, and one scanning ALL COMMENTS OLDER THAN 4 MINUTES UP TO WHEN IT FINDS THAT DB REPLIED every 30 seconds.

**Comment by Snorrrlax** [comment]
That sounds good to me, but feel free to overrule my preference if major downsides arise.

**Comment by hacksoncode** [comment]
Well... I don't think it would save that much by having just one queue that scans all comments, both new and old, back through 4 minutes ago and until it decides to stop. The number of comments in the last 4 minutes is likely to be small compared to the number between now and the last reply. Simpler would seem better. 

I still think that only stopping when it finds a DB reply has some fairly serious failure modes, though.

**Comment by MystK** [comment]
Agreed with @hacksoncode about the high failure of only stopping when finding a DB reply. I'm banking on the new Reddit API module I am trying to use though, and hoping that it will handle the rate limit issues for us. Worst case scenario, I can do a copy paste of the first quees, which saves an array of comments it last looked at.

**Comment by terminak** [comment]
I have not looked at your codebase at all (just stumbled in here), but have you considered just scanning all the comments continuously? In pseudocode:

```python
for comm in subreddit.comments.new(limit=1000):
    if db_has_delta_for(comm):
        if not comment_has_delta(comm):
            remove_delta_from(comm)
    elif comment_has_delta(comm):
        add_delta_to(comm)
```

I do something similar for keeping track of URLs (ninja edits switching wishlists and such), works well for me. But I don't understand the worry about the edit time, so may be overlooking your requirements...

**Comment by RaoulMeyer** [comment]
The problem is that the bot only scans the recent comments up to the last seen comment in the previous run. So if a comment is scanned and afterwards the user edits the comment to contain a delta, that delta will not be awarded. However, to fix this, an extra check was added that scans all comments with the edited flag and processes those again. This still does not fully solve the problem, because if comments are edited within 3 minutes of posting they don't get the edited flag.

Your pseudocode might solve the problem of this issue, I'll have to look at it some more to see if a solution like that would work.

**Comment by Snorrrlax** [comment]
[Here's an example](https://www.reddit.com/r/changemyview/comments/5tnn07/cmv_the_spork_is_an_inferior_utensil/ddnrth7/?context=3) of what we want to prevent with this enhancement.

**Comment by MystK** [comment]
For an update, I am currently working on this

**Comment by MystK** [comment]
Done! Closed and implemented inproduction
