### ISSUE TITLE
Double delta awards

### ISSUE THREAD

**Issue by hacksoncode** [MystK/delta-bot-three#141]
Starting [here](https://www.reddit.com/r/changemyview/comments/5omc9l/cmv_muslims_overreact_to_mohammad_being_depicted/dckgao5/), in subsequent comments there are three separate times where a delta is awarded twice for the same comment. 

Maybe this has something to do with the edited comment code going on line?

**Comment by MystK** [comment]
If I had to guess, I'm thinking it's related to https://github.com/MystK/delta-bot-three/issues/28

I saw that that comment wasn't edited, so the new code never touched this comment.

Luckily, they did not receive a second delta, just a second deltabot comment.

**Comment by hacksoncode** [comment]
Yes, looks like a duplicate of #28, sorry. Closing.
