### ISSUE TITLE
DeltaLog Double Post Bug

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#155]
DeltaBot has made two DeltaLog submissions for one post:

https://www.reddit.com/r/DeltaLog/comments/5rae7w/deltas_awarded_in_cmv_there_is_no_way_of_changing/

https://www.reddit.com/r/DeltaLog/comments/5rae9d/deltas_awarded_in_cmv_there_is_no_way_of_changing/ (This one's undistinguished for some reason).

**Comment by wyantb** [comment]
Doesn't look especially surprising.  That 5rae9d is undistinguished points to a likely cause - if distinguishing the post fails - throwing an error - making the stickied comment will not happen (notice how the stickied comment in OP's post points to 5rae7w, not 5rae9d), and updating the internal wiki log will not happen.  If the wiki log isn't updated, the bot doesn't know about the post it itself made, so it makes it again in the future.

```
/home/brian/repos/delta-bot-three/src/index.js, lines 626-628:
const deltaLogPost = await findOrMakeDeltaLogPost(linkID, comment, parentThing)
const stickiedComment = await findOrMakeStickiedComment(linkID, comment, deltaLogPost)
await updateDeltaLogWikiLinks(linkID, comment, deltaLogPost, stickiedComment)
```

Can't 100% verify without logs and whatnot, but it's fairly likely, and unless it happens at a high rate, might not be too worrying.

**Comment by Snorrrlax** [comment]
Ah! Would it be possible to add some code that says "if distinguishing fails, delete the post", since as you say, DeltaBot will make another one anyway?

**Comment by wyantb** [comment]
In theory maybe, but in practice that'd be hard (impossible?) to do well.  It's not just distinguishing that could cause the problem - if reddit reports a failure for posting which actually succeeded, if making the stickied comment fails or reports a failure after success, if updating the wiki page itself fails or reports a failure after success...well, that's a heck of a lot of things to attempt to roll back in an orderly fashion :)

**Comment by Snorrrlax** [comment]
In that case, let's just leave it (unless you come up with a better solution).

**Comment by MystK** [comment]
Going to have to agree with @wyantb here. We're actually not exactly sure why it failed at that moment. Was it the call itself, or the Reddit API server, or it just crashed? We'd have to answer these questions before being able to solve this issue. Depending on the answers, there are different implementations.

**Comment by Snorrrlax** [comment]
I'll close this, but please re-open if someone has a worthwhile solution.
