### ISSUE TITLE
Minor change to delta history pages

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#158]
At the top of [delta history pages](https://www.reddit.com/r/changemyview/wiki/user/genoscythe_), there's this line:

> ​ /u/Username has received x deltas for the following comments:

Which suggests that what follows is a list of comments that received deltas. Instead, the list links to "delta comments", i.e. the comments that *awarded* deltas (pedantic, I know). It would therefore be more accurate to say "from the following comments", however, I think we should simply cut it down to this:

> ​ /u/Username has received x deltas:

**Comment by arswaw** [comment]
I've opened a PR [here.](https://github.com/MystK/delta-bot-three/pull/172)

**Comment by RaoulMeyer** [comment]
This is now solved.
