### ISSUE TITLE
Admin interface - Basics

### ISSUE THREAD

**Issue by RaoulMeyer** [MystK/delta-bot-three#159]
Basic setup of the admin interface. Consist of a single webpage that connects via a websocket with the backend application. Frontend needs to have some kind of tab structure, switching tabs triggers a message to the server containing some information about the tab that was clicked on. Backend needs a websocket server set up, should be able to receive the tab information and respond with different data depending on the actual tab that was clicked on. For this issue, the server can respond with dummy data and the tabs can be dummy tabs.

**Comment by Snorrrlax** [comment]
Previous discussion on this: #38

**Comment by ozzie1998** [comment]
Just stream the data from the sever to the client, less requests are used that way, and more efficient.

**Comment by MystK** [comment]
What do you mean stream? Is a web socket not streaming the data?

**Comment by ozzie1998** [comment]
Derpdy derp... of course it is. But I think if we can list all the important data the admin interface will require, we can just update the client with that information if any of it had changed, minimising requests going to the server, and hopefully increase performance of the admin interface, or just use a JSON API for all the required information?

**Comment by MystK** [comment]
How is anything you're saying different from the original post? Also a restful API would greatly reduce performance and increase requests don't you think?

**Comment by ozzie1998** [comment]
Of course, I am going mad.

**Comment by MystK** [comment]
Closing due to issue clean up
