### ISSUE TITLE
Admin interface - Reboot and shutdown

### ISSUE THREAD

**Issue by RaoulMeyer** [MystK/delta-bot-three#165]
It should be possible to reboot or shut the bot down from the interface. This somehow needs to be protected from unauthorized users. Triggering one of these actions should make the webpage refresh after a couple of seconds so a new connection can be made if possible.

**Comment by ozzie1998** [comment]
Bump the current process to a new thread, buffer up all the stuff the server requires, on a new thread, start a new server, then sync data, then terminate the old server process, this will allow a quick, in-interrupted service, the admin interface can be protected via HTTPS/SSL, and a login page. I've been wanting to do something like this, so I may start on something like this, then move it over to Reddit.

**Comment by MystK** [comment]
Closing due to issue clean up
