### ISSUE TITLE
Admin interface - Command log

### ISSUE THREAD

**Issue by RaoulMeyer** [MystK/delta-bot-three#168]
The admin should contain a log of each time a command is used (add, delete, force add). Also showing who sent the command and the comment it was used on. Commands should be logged to files, with a separate file for every day.

**Comment by ozzie1998** [comment]
A seperate file for every day would mean something has to monitor the file base to make sure A, all files are there, and that they don't get out of hand, very bad way of doing it! Store it in one JSON file, organised by date, time, etc, one file call, no lookup to find the file you want, etc.

**Comment by ozzie1998** [comment]
I'm working on a system that can search through JSON, and an admin UI based of a NoMysql JSON database, I'll start work on a terminal for it by Friday, after that I'll try and get to work on a web based system, not the most creative btw.

**Comment by MystK** [comment]
Hi @ozzie1998 any PR on this would be greatly appreciated. Thanks :)

**Comment by ozzie1998** [comment]
Sorry, not heard the term PR before, it stands for?

**Comment by Snorrrlax** [comment]
Pull Request

**Comment by ozzie1998** [comment]
Ahh, Of course. Fail.

**Comment by MystK** [comment]
Closing due to issue clean up
