### ISSUE TITLE
Bot hung

### ISSUE THREAD

**Issue by hacksoncode** [MystK/delta-bot-three#176]
Looks like the bot is hung. If someone is around who can debug it, great... otherwise I'm going to reboot it after lunch.

**Comment by MystK** [comment]
I will investigate

**Comment by MystK** [comment]
![image](https://cloud.githubusercontent.com/assets/7399140/23672596/0c0ffbec-0324-11e7-9e60-fcf878323ebc.png)

Looks like the VPS is offline. Maybe related to grabbing yearly deltaboards? @RaoulMeyer

**Comment by MystK** [comment]
It's back up for now. Thanks for monitoring @hacksoncode ;)

**Comment by RaoulMeyer** [comment]
I don't know what would have caused the bot to crash, some logs would be useful. Do the logs of the OS show any cause for the crash?

**Comment by hacksoncode** [comment]
When the VPS has been offline in the past, it has been because of exceeding the memory limit over some mysterious threshold that RamNode has. 

But I thought at some point that we quoted the DB process and had a watchdog, or something...

**Comment by hacksoncode** [comment]
Looks like it might be dead again. No deltas in 6 hours... Seems like perhaps a bigger problem than just a one time glitch.

**Comment by MystK** [comment]
I don't have time today to look at the issue. I've rolled back production to when this wasn't an issue. I will look at this on the weekend. Attached is the log.

I'm pretty sure it has to do with my refactoring.

[out.txt](https://github.com/MystK/delta-bot-three/files/826556/out.txt)

**Comment by RaoulMeyer** [comment]
The last thing the bot was doing before crashing was fetching comments of threads for the yearly deltaboard. Seeing as the memory is very limited, that might be the issue here. Are there any other logs that can confirm that this was a memory issue? How much would it cost to upgrade the VPS to a configuration with more RAM?

**Comment by MystK** [comment]
been three hours. Looking good so far. No logs of memory issues ATM. We are at the cheapest VPS. Not sure on cost, but it's also cheap. Closing this for now unless I see it again.
