### ISSUE TITLE
Add a line space between bullet points in a DeltaLog post.

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#179]
Here's what a DeltaLog post currently looks like: https://www.reddit.com/r/DeltaLogDB3Dev/comments/5z31gw/deltas_awarded_in_cmv_this_should_work/

I'd like to change it to this: https://www.reddit.com/r/DeltaLogDB3Dev/comments/5zyauz/test/

This will make the bullet point lists more readable in /r/DeltaLog, since the link text can sometimes be a bit squashed.

**Comment by yleong** [comment]
I can work on this

**Comment by RaoulMeyer** [comment]
A fix for this issue has been merged.
