### ISSUE TITLE
Deltaboards

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#18]
Delta leaderboards (we'll call them Deltaboards) have been a long desired feature. At one point we had a working monthly leaderboard on our sidebar, the code for which should be somewhere in the [very first DeltaBot script](https://gist.github.com/changemyview/7cb2fec154d709cf584a). This stopped working somewhere along the line and we never got it back, but we'd like to have it again.

Along with the monthly sidebar deltaboard, we'd like a wiki page containing a daily, weekly, monthly, yearly and all-time deltaboard. The template for which has [been set up here](https://www.reddit.com/r/changemyview/wiki/deltaboards).

**Comment by MystK** [comment]
splitting into smaller feature requests
