### ISSUE TITLE
PM acknowledging add/remove commands

### ISSUE THREAD

**Issue by hacksoncode** [MystK/delta-bot-three#182]
The old DB had a feature where it would acknowledge add/remove commands when processed with a PM.

This was very handy, as it's quite awkward to sit there and refresh the screen until DB gets around to removing/adding a delta when you're not sure you formatted the command correctly.

Would it be very hard to add this back?

**Comment by hacksoncode** [comment]
As a side note... I just saw this header on a post where I was trying (unsuccessfully, so far) to remove a delta:

>this page is temporarily in read-only mode due to heavy traffic.

I'm wondering how DB deals with this situation in general. It could be a pretty serious problem for our reliability...

And another good reason to send a PM...

**Comment by Snorrrlax** [comment]
Yeah, PM confirmations would be great.

**Comment by ozzie1998** [comment]
Hmm, I'll take a look tomorrow night, going to read over all the source and figure it all out, and the Reddit API.

**Comment by Snorrrlax** [comment]
Actually, I forgot this would be covered by my suggestion at the bottom of this issue: https://github.com/MystK/delta-bot-three/issues/108
