### ISSUE TITLE
Add ?context=1 to DeltaLog links.

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#183]
For example, [this DeltaLog post](https://www.reddit.com/r/DeltaLog/comments/60uptm/deltas_awarded_in_cmv_transgender_specifically/) contains links like this:

https://www.reddit.com/r/changemyview/comments/60u6bk/cmv_transgender_specifically_mtf_athletes_have_an/df9vb5d/

Can we change all DeltaLog links to include **?context=1** at the end of the URL, like this:

https://www.reddit.com/r/changemyview/comments/60u6bk/cmv_transgender_specifically_mtf_athletes_have_an/df9vb5d/?context=1

**Comment by yleong** [comment]
To achieve this, we can bake `?context=1` into the [i18n template](https://github.com/MystK/delta-bot-three/blob/master/i18n/index.json#L19-L20) directly. 

Or for a more flexible approach, we can modify [mapDeltaLogCommentEntry](https://github.com/MystK/delta-bot-three/blob/master/src/index.js#L425-L431) and add a new key (e.g. `linkParams`) or modify the value of `awardedLink`

**Comment by MystK** [comment]
I am fine with either solution. :) a PR for either is much appreciated!
