### ISSUE TITLE
This edit wasn't rescanned

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#186]
This comment was edited twice. It originally contained a delta in a reddit quote.

In the first edit, the author removed the delta as well as the quote. I replied to them again, and their second edit added it back in. For some reason DeltaBot hasn't rescanned it?

https://www.reddit.com/r/changemyview/comments/622fiq/cmv_living_an_adventurous_life_you_would_remember/dfj8jri/

**Comment by MystK** [comment]
super interesting.

From memory, DeltaBot should always read the edited page linked below.
https://www.reddit.com/r/changemyview/about/edited

It should pick up the edited comment and update it. I'll have to take a look and see what happened.

**Comment by MystK** [comment]
closing for now because a lot of refactoring was done to the code and this could have been fixed
