### ISSUE TITLE
DeltaLog title bug

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#189]
This DeltaLog post says &amp;gt; instead of >

https://www.reddit.com/r/DeltaLog/comments/62mvwx/deltas_awarded_in_cmv_command_pricing_economy_gt/

**Comment by yleong** [comment]
This seems related to #135 where the ampersand was fixed.

According to this [test](https://www.reddit.com/r/DeltaLogDB3Dev2/comments/64juff/deltas_awarded_in_cmv_dont_get_stuck_in_a_closet/) both < and > are currently affected so I will fix for both.

**Comment by Snorrrlax** [comment]
Are there any other characters/symbols that might be affected in this way?

**Comment by yleong** [comment]
According to [this](https://stackoverflow.com/questions/1091945/what-characters-do-i-need-to-escape-in-xml-documents), it seems like < > " ' & are the only characters.

**Comment by Snorrrlax** [comment]
Ah I see, thanks!
