### ISSUE TITLE
Double Sticky Comment

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#193]
This post has two "sticky comments" from DeltaBot: https://www.reddit.com/r/changemyview/comments/65ctl4/cmv_i_believe_i_have_legitimately_solved_the/

Only one is actually stickied of course, but DeltaBot made the comment twice (the second is further down the comments).

**Comment by MystK** [comment]
Looks like what happened is that DeltaBot crashed or something midway to awarding and making a comment. It's hard to fix this at the source, and we'll most likely need another thread running looking for Deltabot mistakes like this.

**Comment by yleong** [comment]
Even so, when DeltaBot recovers and tries to sticky-comment again, wouldn't it have detected the existing sticky-comment and stop proceeding? 
Unless DeltaBot recovers faster than Reddit can update and causes a race-condition?

**Comment by Snorrrlax** [comment]
This happened again today, six times within the same post:

https://www.reddit.com/r/DeltaLog/comments/6cqv28/deltas_awarded_in_cmv_people_should_earn_the/
https://www.reddit.com/r/DeltaLog/comments/6coa0f/deltas_awarded_in_cmv_people_should_earn_the/
https://www.reddit.com/r/DeltaLog/comments/6cpgvx/deltas_awarded_in_cmv_people_should_earn_the/
https://www.reddit.com/r/DeltaLog/comments/6cnbn1/deltas_awarded_in_cmv_people_should_earn_the/
https://www.reddit.com/r/DeltaLog/comments/6cmzu8/deltas_awarded_in_cmv_people_should_earn_the/
https://www.reddit.com/r/DeltaLog/comments/6cmx6x/deltas_awarded_in_cmv_people_should_earn_the/

**Comment by ardaozkal** [comment]
https://www.reddit.com/r/DeltaLog/comments/6w15if/deltas_awarded_in_cmv_everyone_cant_code/
https://www.reddit.com/r/DeltaLog/comments/6w16nv/deltas_awarded_in_cmv_everyone_cant_code/
https://www.reddit.com/r/DeltaLog/comments/6w1seg/deltas_awarded_in_cmv_everyone_cant_code/
https://www.reddit.com/r/DeltaLog/comments/6w59n7/deltas_awarded_in_cmv_everyone_cant_code/

---

https://www.reddit.com/r/DeltaLog/comments/6w2bjg/deltas_awarded_in_cmv_all_teachers_should_be_hot/
https://www.reddit.com/r/DeltaLog/comments/6w1m3c/deltas_awarded_in_cmv_all_teachers_should_be_hot/

---

https://www.reddit.com/r/DeltaLog/comments/6w04vp/deltas_awarded_in_cmv_some_cuisines_dont_have/
https://www.reddit.com/r/DeltaLog/comments/6vzod2/deltas_awarded_in_cmv_i_dont_think_we_should/
https://www.reddit.com/r/DeltaLog/comments/6vziag/deltas_awarded_in_cmv_i_dont_think_we_should/

---

https://www.reddit.com/r/DeltaLog/comments/6vzd6a/deltas_awarded_in_cmv_some_cuisines_dont_have/
https://www.reddit.com/r/DeltaLog/comments/6vzrbe/deltas_awarded_in_cmv_some_cuisines_dont_have/
https://www.reddit.com/r/DeltaLog/comments/6w04vp/deltas_awarded_in_cmv_some_cuisines_dont_have/

etc etc

**Comment by Snorrrlax** [comment]
https://www.reddit.com/r/DeltaLog/search?q=the+military+budget&restrict_sr=on
