### ISSUE TITLE
This delta cannot be added

### ISSUE THREAD

**Issue by whitef530** [MystK/delta-bot-three#195]
https://www.reddit.com/r/changemyview/comments/68fihe/cmv_porn_is_normal_and_does_not_have_a_negative/dh0pgkh

Two issues:

1. DB doesn't automatically rescan the edited comment
2. DB doesn't respond to the add command

**Comment by MystK** [comment]
Not sure why the auto rescan doesn't work, but the add doesn't work because DB3 detects that it has replied already. You'll have to send a delete, then add.

**Comment by MystK** [comment]
saw that this was fixed
