### ISSUE TITLE
Adding "deltas given" to delta history

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#196]
I was reading through some old DeltaBot feature discussions, and an idea that came up was keeping track of users who *give* deltas as well as those who receive them.

I don't think it would be a good idea to make a separate user flair system or more deltaboards, but a section in a user's delta history page would be a nice addition. I chose a reasonably sized delta history page from our current monthly deltaboard, copied it over to a draft page, and made some changes to get an idea:

https://www.reddit.com/r/changemyview/wiki/user/testtesttest

**Comment by MystK** [comment]
Cool feature. A lot of what's required is already implemented. Completing this task requires using the features we currently have and doing some refactoring.

For whoever does this, it would be good to convert this section of the code to use snoowrap also.

**Comment by MystK** [comment]
deployed! THanks again!
________________________________
