### ISSUE TITLE
Character length required to award delta

### ISSUE THREAD

**Issue by MystK** [MystK/delta-bot-three#2]
What is the character length required to award a delta? This is a note to myself to look, but if anyone can comment, it would save me some time digging. it is currently set to 50 characters.

CC: @Snorrrlax

**Comment by Snorrrlax** [comment]
We're a bit confused about what it's currently set at. MARS was set at 50 ([see here](https://github.com/PixelOrange/MARS/blob/master/settings/config.json.example)) and the original one set at 100 ([see here](https://github.com/alexames/DeltaBot/blob/master/config/config.json.example)). I think 50 is good for now, we can always change it.

**Comment by MystK** [comment]
Closing as it's currently set to the correct value.
