### ISSUE TITLE
Bot seems up, but not responding to email

### ISSUE THREAD

**Issue by hacksoncode** [MystK/delta-bot-three#20]
I've tried sending "add" requests for several deltas lately, including these (some of which are deleted comments, so no worries there), and none of them are coming through.

They don't look edited, but who knows. Anyway, rather than just kick the bot again I thought I'd report it in case debugging live is useful. 

https://www.reddit.com/r/changemyview/comments/4rcqak/cmv_it_should_not_be_legal_in_the_west_to_be_a/d4zziis

https://www.reddit.com/r/changemyview/comments/4r8bhu/cmv_paternity_tests_should_be_mandatory_at_all/d4z544v

https://www.reddit.com/r/changemyview/comments/4r8bhu/cmv_paternity_tests_should_be_mandatory_at_all/d4z6w8c

https://www.reddit.com/r/changemyview/comments/4r2kxd/cmv_the_best_way_to_deal_with_annoyingnasty/d4xwa6l

https://www.reddit.com/r/changemyview/comments/4r2kxd/cmv_the_best_way_to_deal_with_annoyingnasty/d4xw1ii

https://www.reddit.com/r/changemyview/comments/4r2bt4/cmv_i_think_having_kids_right_now_in_cruel/d4xqoo9

https://www.reddit.com/r/changemyview/comments/4qv031/cmv_there_is_no_plausible_ending_for_the_song_of/d4w7usm

https://www.reddit.com/r/changemyview/comments/4qujd2/cmv_barack_obama_is_the_43rd_president_of_the/d4w1f13

**Comment by MystK** [comment]
Fixed. It was an issue with DB3 and accessing wikis
