### ISSUE TITLE
DeltaLog Entry Bug

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#200]
Link didn't work: https://www.reddit.com/r/DeltaLog/comments/6fhrse/deltas_awarded_in_cmv_the_evergreen_state_college/

**Comment by mchav** [comment]
Could you give more details on this problem? Which link didn't work?

**Comment by Snorrrlax** [comment]
Sorry for the delay @mchav, I missed your question. In this DeltaLog post, the link text for [this comment](https://www.reddit.com/r/changemyview/comments/6fhfzw/cmv_the_evergreen_state_college_situation_is_not/dii7hcx/?context=1) failed, and was posted as:

> "[Evergreen State College has an enrollment of 4,416 and even in liberal Washington State has been the butt of jokes for years (even if they do have a hilarious mascot and fight song). Per Wiki: [Quote...](https://www.reddit.com/r/changemyview/comments/6fhfzw/cmv_the_evergreen_state_college_situation_is_not/dii7hcx/?context=1)"

Instead of:

> "[Evergreen State College has an enrollment of 4,416 and even in liberal Washington State has been the butt of jokes for years (even if they do have a hilarious mascot and fight song). Per Wiki: [Quote]...](https://www.reddit.com/r/changemyview/comments/6fhfzw/cmv_the_evergreen_state_college_situation_is_not/dii7hcx/?context=1)"
