### ISSUE TITLE
Missed delta, can't add using PM (was: New delta character U+2206)

### ISSUE THREAD

**Issue by hacksoncode** [MystK/delta-bot-three#206]
Please ignore this comment and only look at the next one, leaving this here for history: Somehow a user found this unicode character: ∆ (U+2206). Its description is "increment".

Rather than try to create explanations about this, can we just add this to the set of characters we accept?

https://www.reddit.com/r/changemyview/comments/6vurox/cmv_i_want_to_get_cosmetic_jaw_surgery/dm3nbrc/

**Comment by hacksoncode** [comment]
Never mind... my mistake... that's the normal one (8710 in decimal).

However, for some reason DB failed to award a delta on this one... maybe an escape from our editing rescan? An add command doesn't work on this.

**Comment by MystK** [comment]
This was fixed in fa76a83ac5ad195e046b9747bf74eed59846ac59.

We were not using the same "check for delta" function in the add messages vs everywhere else. I've fixed that.
