### ISSUE TITLE
User reports seeing the hidden text on iPhone reddit app

### ISSUE THREAD

**Issue by hacksoncode** [MystK/delta-bot-three#21]
A user (https://www.reddit.com/user/el3r9) has reported that they can see the hidden text on a delta message in the iOS reddit app. Here's the comment where they mention it... 

https://www.reddit.com/r/changemyview/comments/4rmxwp/cmv_you_cant_be_a_social_democrat_fiscal/d52mv4x

Wasn't sure whether you were ok with my sending random people your username for things like this.

**Comment by JohnnyO** [comment]
Confirmed, I just checked it in the Reddit app, screenshot is below

https://imgur.com/a/spjqY

**Comment by MystK** [comment]
Thanks! Glad I put that comment there. :) please forward all issues to this repo and I'll knock them all out!

**Comment by MystK** [comment]
Did some investigating. Not a bug with DB3. It is due to the Reddit app. It does not correctly support markdown. Normally I'd just close this out, but I will leave this open as I will try to work around the Reddit app's bug.

**Comment by hacksoncode** [comment]
I wonder if it's because of the empty brackets... Maybe try using the
period at the end of the sentence as the "link text"?

-- 
Ray

**Comment by MystK** [comment]
Pretty sure you're spot on! That + maybe the new line characters.

**Comment by MystK** [comment]
Thanks hacksoncode. Added a "." inside of the "[]" and it worked!
