### ISSUE TITLE
Users giving Deltas to themselves

### ISSUE THREAD

**Issue by whitef530** [MystK/delta-bot-three#217]
This user was able to self-award a delta:

https://www.reddit.com/r/changemyview/comments/7grmx0/cmv_a_dna_test_should_be_required_to_be_listed_as/dqllm1g/

Can we disallow self-awarded deltas, just like deltas awarded to OP?

**Comment by MystK** [comment]
That's odd as I thought we have code in here already to disallow awarding a delta to yourself. A left over debug mode maybe made it into production?
________________________________

**Comment by wyantb** [comment]
Yeah, we have code for that. All the comments linked are deleted there so I can't really see what's going on...did they make another user with similar-looking names that aren't identical, like bIb and b1b or something?

/Users/brianwyant/repos/delta-bot-three/src/utils.js, lines 87-93:

```
if (parentThing.author === author && author.toLowerCase() !== 'mystk') {
  console.log(`BAILOUT parent author, ${parentThing.author} is author, ${author}`)
  const text = i18n[locale].noAward.self
  issues.self = 1
  if (query.text.length) query.text += '\n\n'
  query.text += text
}
```

**Comment by Snorrrlax** [comment]
@wyantb, I've temporarily re-approved these comments so you can check them.

**Comment by wyantb** [comment]
Hmm, don't see anything funny there. Maybe we should be using `author.name` here? An earlier guard indicates that our data may not be clean as the code is assuming:

/Users/brianwyant/repos/delta-bot-three/src/utils.js, line 64:

```
if ((author.name || author) === botUsername) return true
```
