### ISSUE TITLE
[∆(s) from OP] flair missing

### ISSUE THREAD

**Issue by whitef530** [MystK/delta-bot-three#218]
I've noticed several threads recently where despite being deltas awarded from the OP, there is no [∆(s) from OP] flair, which had to be added manually.

https://www.reddit.com/r/changemyview/comments/7i22gb/cmv_donald_j_trump_should_have_been_times_person/?st=jaxdk8au&sh=48f1601f

https://www.reddit.com/r/changemyview/comments/7i9rco/cmvbackstabbing_democrats_are_making_me_starting/?st=jaxdhtwz&sh=dd3f655f

**Comment by MystK** [comment]
Hmm, are you sure it's not because the flair you see is actually saved at that point in time?

EX: after a delta comment, the flair of the comment being deltaed actually does not get updated. You only see it when the user comments again.

I've had this happen to me also.

**Comment by Snorrrlax** [comment]
AutoModerator is the bot that updates link flair. It does it regardless of whether DeltaBot awards a delta, because its config is set to "if OP comment contains delta, update flair"

**Comment by MystK** [comment]
closing because not related to db3
