### ISSUE TITLE
Rejecting sufficiently long comments

### ISSUE THREAD

**Issue by hacksoncode** [MystK/delta-bot-three#22]
I was looking through /u/DeltaBot today, and I found a lot of "rejected for too short" comments by the both lately... I looked through the code and it looks like it's supposed to be checking for 50+ characters...

However, several of the rejected comments seem to be longer. For example, this one: https://www.reddit.com/r/changemyview/comments/4rqb4v/cmv_accepting_riots_in_the_black_community_as/d54fc89

... which is ~75 characters long. I'm not seeing any evidence that it's edited, either...

There are other examples too...

**Comment by MystK** [comment]
99% sure they edit it before the 3-5 minute mark. Will leave this open for now

**Comment by MystK** [comment]
Verified that all is working. They just edit within the edit timer so the * is not shown.
