### ISSUE TITLE
DeltaBot didn't ignore this quoted delta

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#220]
Here: https://www.reddit.com/r/changemyview/comments/7nqgf9/cmv_i_envy_narcissists/ds3rtgh/

**Comment by hacksoncode** [comment]
I think there might be an existing issue related to "!delta" not being "protected" by reddit quotes.

**Comment by MystK** [comment]
This is because db3 was stupid and only removed the first quoted area
