### ISSUE TITLE
DB repeated delta awarded message several times

### ISSUE THREAD

**Issue by whitef530** [MystK/delta-bot-three#221]
https://www.reddit.com/r/changemyview/comments/7o42do/cmv_beginning_in_high_school_american_students/ds6wr05/

**Comment by wyantb** [comment]
Looks like a duplicate of #184. @Snorrrlax are you OK with closing this one out to consolidate into the other?

**Comment by Snorrrlax** [comment]
Sure!

**Comment by Snorrrlax** [comment]
Actually, is it definitely a duplicate? Because these extra comments are undistinguished, but in the other issue they're both distinguished.

**Comment by wyantb** [comment]
They've probably got similar enough root causes. A comment in the other one linking this post and describing how they're subtly different would go a long way if you're worried.
