### ISSUE TITLE
Missing deltas during yesterday's down time

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#227]
DeltaBot hasn't scanned back through comments to find those missed during a period of 12 hours. Can we force it to?

**Comment by MystK** [comment]
I had tried to reset DB3 to it's state before it crashed and I thought it grabbed all the deltas.

One thread I saw that it was missing deltas was:

https://www.reddit.com/r/changemyview/comments/7xj2sz/cmv_under_us_common_law_illegal_immigrants/

Are there any other cases of missing deltas?

**Comment by Snorrrlax** [comment]
As far as I'm aware, it only started awarding new deltas when it was rebooted. I saw quite a few old ones that were missed, and we received a few messages asking about it. 

We had to use the add command on this one: https://www.reddit.com/r/changemyview/comments/7xirrw/cmv_fisking_is_a_good_way_to_reassure_people_who/du8kt0r/

**Comment by MystK** [comment]
closing to move this to #243
