### ISSUE TITLE
New delta token

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#229]
Please add the following HTML entity as a delta token:

**&amp;Delta;** (needs the capital letter)

**Comment by MystK** [comment]
Is that why we miss deltas sometimes?

**Comment by hacksoncode** [comment]
It's hard to say... it depends on whether you get a translated string or raw HTML when looking at the comment body. If the latter, it wouldn't surprise me, but I've never actually seen anyone use this when I've done a show-source on a post. On the other hand, it's rare that I've done that...

**Comment by wyantb** [comment]
/home/brian/repos/delta-bot-three/src/utils.js, lines 21-24:

```
if (
  !!removedBodyHTML.match(/&amp;#8710;|&#8710;|∆|Δ/) ||
  !!removedBodyHTML.match(/!delta/i)
) {
```

Seems to already be using a case-insensitive matching - that's the `/i` part of the `!delta/i`...on the other hand, we accept `!delta` but not `&delta`. So accepting the latter as well would be trivial.
