### ISSUE TITLE
Something is not right with the bot

### ISSUE THREAD

**Issue by hacksoncode** [MystK/delta-bot-three#23]
I'm not sure what's up, but I restarted the server because the bot was being non-responsive, and I believe I logged in and ran the instructions given to start it (the auto-start seems to still be broken, because I saw the "SCREEN -dmS db3 bash -c cd ~/delta-bot-three/; nvm use; npm start ; exec bash" in the process list, but no node process or nvm process). 

However, there was a 403 error during login, and also when I sent it an "add" message, it showed a log message saying that the linked comment was good and that it should award it, but no delta message was added. Also, it's retrying every 10 seconds to get the wiki page for the awarded user, and failing with a 404.

**Comment by MystK** [comment]
will investigate today.
