### ISSUE TITLE
Investigate crashing issue

### ISSUE THREAD

**Issue by MystK** [MystK/delta-bot-three#235]
![image](https://user-images.githubusercontent.com/7399140/36654504-f8813792-1a71-11e8-8e32-1ba6c2f467ac.png)

Logs are not too helpful. Just says that it crashed.

**Comment by wyantb** [comment]
Shame. Toss in some verbose? https://github.com/remy/nodemon/blob/master/faq.md#what-does-verbose-give-me

**Comment by MystK** [comment]
after the major refactor to make the main module use the "modules" system, I havn't seen any crashes in days. closing for now
