### ISSUE TITLE
Missed delta edit

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#238]
This edit was missed: https://www.reddit.com/r/changemyview/comments/815ycg/cmv_2_weetabix_is_the_correct_number_of_weetabix/dv0wqng/

**Comment by ntravis** [comment]
Similarly, parent of [this comment](https://www.reddit.com/r/changemyview/comments/818b97/cmv_conservatives_on_reddit_are_the_fragile/dv1q8ga/?context=1000) was edited and bot didn't update.

**Comment by MystK** [comment]
thanks to both for catching. manually added. closing

**Comment by MystK** [comment]
this was due to the bot having debug code and the check edited comments was not running. it's now officially fixed.
