### ISSUE TITLE
DB stole my deltas

### ISSUE THREAD

**Issue by hacksoncode** [MystK/delta-bot-three#24]
Serious stuff, these fake internet points!!!! :-)

DB lost about 15 of my deltas, as can be seen from these subsequent history snapshots of my delta history:

https://www.reddit.com/r/changemyview/wiki/user/hacksoncode?v=27292d34-3d3d-11e6-9547-0e03d6a53fed

https://www.reddit.com/r/changemyview/wiki/user/hacksoncode?v=163fc9c6-491b-11e6-9bca-0e1b9dda2b81

**Comment by MystK** [comment]
It has to do with the way DB3 counts deltas. Before it would be current flair + 1. Now it is length of awarded delta history.

**Comment by hacksoncode** [comment]
Hmm... So it's probably only a problem for people that earned deltas before
the old deltabot tracked history...

I wonder if there's any way to fake something up for those old timers...
There are quite a few of us.

There are also some number of instances where the mods hand-awarded Deltas
by editing flair because the bot was broken.
-- 
Ray

**Comment by MystK** [comment]
Yes it's possible to fake it, ;). Just gotta add empty deltas to the hidden JSON. I'll add 13 deltas to your wiki, unless you can do it. It will update once you receive a delta.

Once everything is finished, I'll close this ticket.

**Comment by hacksoncode** [comment]
I figured I could probably fake it in my particular case... I'm more
wondering if there's some way to fix the problem systematically for
everyone...

It should be possible, though perhaps a little difficult, to notice that an
existing history page has a delta count at the top that is different from
the history length.

That wouldn't help anyone who lost deltas already from the issue, I
guess... Maybe we will have to rely on reports to fix those...
-- 
Ray

**Comment by MystK** [comment]
Adding a note that aidrocsid lost deltas also during the migration to the new wiki table. Putt it here for note for myself

**Comment by hacksoncode** [comment]
Another case of mysterious delta vanishing... This one might be the same or it might be different, not sure.

The person's wiki entries seem to have mysteriously disappeared from a version 12 days ago as well as their delta count.

Anyway: [current wiki](https://www.reddit.com/r/changemyview/wiki/user/mpixels), [version from 12 days ago](https://www.reddit.com/r/changemyview/wiki/user/mpixels?v=10d35124-5aa0-11e6-ad4a-0ebd8530edcf)

**Comment by MystK** [comment]
I fixed your deltas. Not sure what happened with that person but I manually fixed it also.

As the hidden DB3 params, it's not too complex. It's just JSON.

See below
```
{
  "comment": "This is hidden text for DB3 to parse. Please contact the author of DB3 if you see this",
  "deltas": [
    {
      "b": "/r/changemyview/comments/36d2wf/cmv_the_lid_of_the_toilet_serves_no_purpose/",
      "dc": "crcwt0s",
      "t": "CMV: The lid of the toilet serves no purpose.",
      "ab": "TheGrandDalaiKarma",
      "uu": 1431956441
    },
    {
      "b": "/r/changemyview/comments/36u3s6/cmv_common_usage_of_xe_or_other_gender_neutral/",
      "dc": "crhaveu",
      "t": "CMV: Common usage of \"xe\" or other gender neutral pronoun would improve/make English language easier.",
      "ab": "solomon34",
      "uu": 1432290339
    },
    {
      "b": "/r/changemyview/comments/49ty6s/cmv_if_i_cannot_submit_my_cv_for_consideration_to/",
      "dc": "d0uvvkv",
      "t": "CMV: If I cannot submit my CV for consideration to be the next King of England, the monarchy is illegitimate.",
      "ab": "DrDerpberg",
      "uu": 1457629960
    },
    {
      "b": "/r/changemyview/comments/4c56ox/cmv_the_whole_fine_bros_thing_with_their_reaction/",
      "dc": "d1f6fev",
      "t": "CMV: The whole Fine Bros thing with their reaction videos seems like a major overreaction to me and I see nothing wrong with it.",
      "ab": "kinpsychosis",
      "uu": 1459083195
    },
    {
      "b": "https://www.reddit.com/r/changemyview/comments/4oxzkh/cmv_uniforms_and_strict_dress_codes_should_be/",
      "dc": "d4gi19j",
      "t": "CMV: Uniforms and strict dress codes should be enforced in schools.",
      "ab": "hellknight101",
      "uu": 1466421337
    },
    {
      "b": "https://www.reddit.com/r/changemyview/comments/4w7gbf/cmvas_a_democrat_i_hate_trump_and_dont_trust/",
      "dc": "d64oitz",
      "t": "CMV:As a democrat I hate Trump, and don't trust Hilary. I want to vote third party.",
      "ab": "spigs5",
      "uu": 1470355393
    },
    {
      "b": "https://www.reddit.com/r/changemyview/comments/4y1kiv/cmv_speed_runners_should_be_benchmarked_on/",
      "dc": "d6k9n03",
      "t": "CMV: Speed Runners should be benchmarked on completing games without glitching",
      "ab": "LuckMaker",
      "uu": 1471382763
    },
    {
      "b": "https://www.reddit.com/r/changemyview/comments/4y63ou/cmv_beowulf_is_a_dumb_story/",
      "dc": "d6l8tyw",
      "t": "CMV: Beowulf is a dumb story.",
      "ab": "edcokn",
      "uu": 1471448335
    },
    {
      "b": "https://www.reddit.com/r/changemyview/comments/4yin4z/cmv_i_believe_installing_death_traps_on_a_hidden/",
      "dc": "d6o1mhm",
      "t": "CMV: I believe installing death traps on a hidden room is totally justified. I see no shortcomings. (safe house of the futureAXDK9vhFALCkjXPmwvSB",
      "ab": "Garlicplanet",
      "uu": 1471615424
    }
  ]
}
```

DB3 depends on reliable data. Text is not reliable data, so JSON is used. The table is generated from this JSON, which could be edited.

Closing because fixed! :)
