### ISSUE TITLE
Temporarily change message on comments that are too short

### ISSUE THREAD

**Issue by hacksoncode** [MystK/delta-bot-three#27]
Looks like issue #4 may take a while to get working.

Can I suggest a temporary alternative?

Can we change the message to the users when their delta comment is too short to ask them to repost a new comment that is longer? Right now they think they can just edit the old one, which is... awkward to explain. 

Then after we decide the feasibility of #4 we can decide on a permanent message to change it (back?) to?

**Comment by MystK** [comment]
Hello. Good idea and sorry that it's taken this long. Can someone create copy to replace this?

**Comment by hacksoncode** [comment]
How about:

"This delta has been rejected. The length of your comment suggests that you haven't explained how /u/fayryover changed your view (comment rule 4). In the future, DeltaBot will be able to rescan edited comments. 

In the mean time, please repost a new comment with the required explanation so that DeltaBot can see it."

While you're at it, I also noticed at least one DB comment that said (paraphrasing):

"You have 2 problems: <too short, please edit> and <cannot award a comment to OP>"

Probably the second one should just override the first one. We don't want to confuse commenters by saying they should edit/repost their comments when it *still* won't be accepted because they can't award to OP.

**Comment by MystK** [comment]
i18n has been updated and the error messages are either or now
