### ISSUE TITLE
DeltaBot confirmation comment

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#32]
Low priority again. Inspired by the proposed Deltaboard format - can we update DeltaBot's confirmation comment (and the footnotes) to this?

> Confirmed: 1 delta awarded to garnteller ([181&#8710;](https://www.reddit.com/r/changemyview/wiki/user/garnteller "garnteller's delta history wiki page")).
>
> [Delta System Explained](https://www.reddit.com/r/changemyview/wiki/deltasystem) | [Deltaboards](https://www.reddit.com/r/changemyview/wiki/deltaboards)

**Comment by Snorrrlax** [comment]
The arrows don't seem to work here?

**Comment by MystK** [comment]
This is good, easier for me to copy paste ;)

**Comment by roastchicken** [comment]
You edited the footer; do you want them to be subscript or just normal text?

**Comment by roastchicken** [comment]
I assumed that you wanted it to be in subscript, but go ahead and let me know (here or on the pull request) if that's not what you want and I'll change it.

**Comment by Snorrrlax** [comment]
Yes superscript please. Thanks!

**Comment by roastchicken** [comment]
Oh, yeah, superscript. Not sure why I got them mixed up.

**Comment by MystK** [comment]
PR brought in and in production.
