### ISSUE TITLE
Feasible solution to missing deltas?

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#33]
This issue is more of a discussion starter since there doesn't seem to be a clear solution at the moment.

I'm not sure we know how many people have been effected, but let's take one of our mods /u/TryUsingScience as an example, who has lost deltas. This was the suggested solution:

> DB3 lost your deltas because the first version of V0 linked to the CMV post and not the actual comment. You can go multiple routes.
> First, find the links of people giving you deltas.
> If it is archived and DB3 can't make any comments, you have to edit the JSON on your wiki and add an entry. It will be picked up on your next delta award.
> If DB already replied to your delta, but it's not in the wiki, send DB a "delete" message. delete in subject and in the body, the link to the comment giving you a delta. You can fit multiple delta comments on each line. After the comment gets deleted, send it the "add" message. Same thing as the delete except with add as the subject.
> If DB did not reply, just send the "add" message.

However, since she estimates to have lost 60+ deltas, this isn't very feasible. 

Here's my thoughts:

If the deltas effected were given at the time of DB version 0, then that means they likely had [an old user wiki page](https://www.reddit.com/r/changemyview/wiki/tryusingscience), that used the url format of /wiki/username, rather than what we have now: /wiki/user/username. 

/u/PixelOrange migrated all of the pages during our time using DB version 2. 

The reason I bring it up, is because on a wiki page you can [see a list of revisions](https://www.reddit.com/r/changemyview/wiki/revisions/tryusingscience) which you can revert back to. 

I wonder if it would be possible to create a separate script for DeltaBot to go through all the wiki page histories to find the correct totals?

Here's a full wiki page list: https://www.reddit.com/r/changemyview/wiki/pages/

**Comment by MystK** [comment]
TryUsingScience lost so many deltas because DB3 verifies each awarded delta. 

When DB3 looked through TryUsingScience's wiki, https://www.reddit.com/r/changemyview/wiki/user/tryusingscience?v=46974a96-97cc-11e5-a617-0e556a3929f5 and https://www.reddit.com/r/ChangeMyView/wiki/userhistory/user/tryusingscience

DB3 searched for delta comments, only finding 7. 9 delta links in the wiki were to the CMV post itself(not supported), and 24 were undocumented. I checked the old user wiki page, and 24 deltas are still unaccounted for.

I actually manually went through all the V0 links, and I only found 13 delta comments, so 11 are still unaccounted for. Out of the 13 comments, many of them would not satisfy the "long enough" rule.
LINKS
https://www.reddit.com/r/changemyview/comments/1bv9w5/i_think_cuttersselfharmers_are_mentally_weak_and/ 8 deltas
1 delta awarded to /u/TryUsingScience 3 deltas
https://www.reddit.com/r/changemyview/comments/1glv5k/i_think_its_hypocritical_that_if_a_pregnant_woman/ 1 delta
https://www.reddit.com/r/changemyview/comments/1h6vd4/i_think_the_filibuster_should_be_ended_cmv/ 1 delta

A script to go through the past wiki pages and history wouldn't help too much in this case.

My proposal would be to handle this case by case. A user pleads that his deltas are missing from the past. Someone verifies and approved X deltas to be added. The hidden data can be edited by anyone to add these deltas. I can write up a quick doc on how to edit the hidden data in the wiki. It is pretty straightforward. Thoughts?

**Comment by Snorrrlax** [comment]
Okay so if a delta is absolutely undocumented, I think we'll just have to deal with losing those ones (unless like you say the user themselves is willing to find and send them to us). 

It's possible that some of TUS's original deltas were awarded manually by me before we had a functioning DeltaBot (she was around near the very start). 

It would probably be very useful to have a public announcement/document type thing explaining clearly how to go about getting deltas back if a user has lost them.

The above is for completely undocumented deltas. However, for deltas that are documented but not verified, or just linked to the post, I'd be willing to source someone to write a script for this separate from DB3 (if you don't have the time) as I think it would be most likely that people wouldn't want to bother sorting through old delta comments (especially if they have lots) and so our all-time leaderboard may not be completely accurate.

Having said all that, if there really is no way then that's that! I don't want to distract from more important DB progress.

**Comment by MystK** [comment]
**ACTION ITEMS**
Me
- Create document explain the hidden params and how to add deltas to the wiki to up the flair count

Anybody
- Create a script independent of DB which looks through Wiki revisions for MISSING deltas and adds them to the hidden params.
- NOTE: From an engineer's perspective, the difficulty of this will be HIGH

**Comment by Snorrrlax** [comment]
Okay, thank you.

If we were to go down the separate script route, is there anything the person doing it would need to know? 

Would it have to be written in the same language (I assume not)?

**Comment by Snorrrlax** [comment]
What about scanning through DeltaBot's entire comment history and tallying up each user's delta count from scratch? A long list, but potentially a simpler script?

**Comment by MystK** [comment]
I've tried to scan DB's entire comment history and it looks like the API caps us at the last 1000 comments. I can do a double check of this later.

For the separate script route, The person writing it would have to know where to put the missing deltas data(in the hidden parameters in the wiki)

**Comment by MystK** [comment]
It can be in any language. No probs at all.

**Comment by Snorrrlax** [comment]
Just did a quick google, does this help at all? https://youtu.be/W6_te6Q_CDs?t=904

**Comment by MystK** [comment]
Thanks for checking, unfortunately not too much. I know there are a bunch of ways of grabbing the data we need, but it just takes some time to develop. To create a script to do a reconciliation of all awarded deltas, I'd estimate at least a week of full time work.

**Comment by Snorrrlax** [comment]
Ah I see. We'd definitely rather your efforts were focused on the current DeltaBot roadmap. 

Is there any chance you could write up a post advertising the help needed over on /r/programming, /r/coding, /r/python etc? I feel like someone who knows what they're talking about would do better. No worries if you can't, I appreciate you're busy!

**Comment by roastchicken** [comment]
If https://github.com/eleweek/SearchingReddit (project mentioned in the video Snorrlax posted) isn't defunct, couldn't we use that? It seems like a good starting place, at least. It seems that it allows us to download the entire subreddit and then search through it; isn't that pretty much what you were asking for right @Snorrrlax ? Maybe tweaking it slightly to make it only target DeltaBot's comments.

**Comment by MystK** [comment]
Yes, that’s the first step of grabbing missing deltas. Get all comments from DeltaBot. Get all comments from CMV subreddit is also good. With that data, we’ll be able to figure out valid deltas.

**Comment by JohnnyO** [comment]
There are lots of threads and comments that have likely been deleted, especially if they are years old.  I think we might want to avoid requiring that the original thread and post still exist.  It's less elegant, but I think we can assume that if they had a delta in the past, it was counted correctly.  A simpler solution might be to simply start with the number they had pre-DB3, and then accumulate new ones.

**Comment by Snorrrlax** [comment]
Is there a way to find old delta scores?

**Comment by MystK** [comment]
Yes, I’d say from the delta count on the wiki. It’s possible to artificially inflate the deltas based on what we see in the older revisions of a user’s wiki. It would be unverified data though.

**Comment by Snorrrlax** [comment]
Can you explain what you mean by unverified and why this is important?

**Comment by MystK** [comment]
Yes, all deltas awarded at the moment have been verified by the bot.

Verified as in, there is a link to the actual comment in the wiki.

**Comment by Snorrrlax** [comment]
If we were to use the unverified totals from the old wiki pages, would this be a much easier task?

**Comment by MystK** [comment]
Yes, tons easier.

**Comment by Snorrrlax** [comment]
Would you be willing to do that, or still rather outsourcing?

**Comment by MystK** [comment]
Ya, I'd be willing to do anything, really, whether it's this or writing that separate application. It's just that everything takes time, so as long as you have a roadmap for me, I know what to focus on next ;)

**Comment by Snorrrlax** [comment]
Let's go with #35 for now
