### ISSUE TITLE
Missing Deltas - Quicker Fix

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#35]
By the looks of it, a completely separate script that scrapes the entire subreddit for missing deltas probably won't happen soon. If someone approaches us who's willing to do it, great, but for now let's go with this:

As discussed in #33, the old user wiki pages contained delta counts of unverified deltas. They weren't completely accurate in a lot of cases, but in the interest of having a quick fix that keeps the majority of people happy, let's grab them and update delta scores. 

We could provide the option for anybody still not happy to manually add them - or have DeltaBot scan their PMs - if they provide us with links.

And then maybe one day we'll have that separate script that finds every single delta!

**Comment by Snorrrlax** [comment]
As a clear example for anyone reading this, /u/Amablue's [old](https://www.reddit.com/r/changemyview/wiki/userhistory/user/amablue) and [new](https://www.reddit.com/r/changemyview/wiki/user/amablue) wiki pages don't match up.

**Comment by AHarman** [comment]
So, for a given user, go through both their wiki pages (the old one at /wiki/user/[username] and the new one at /wiki/userhistory/user/[username]), find all the awards in the old that aren't in the new and add them in to the new page? 

There are also pages that are just /wiki/[username], but those are completely obsolete (the text in the couple I checked just had a message stating they'd been migrated).

**Comment by Snorrrlax** [comment]
Yes except you have the old and new the other way around. I'm not sure how any of this will work since I don;t code, but I'm just trying to initiate it.

Yeah, for some reason the old pages were moved from wiki/username to wiki/userhistory/username, and new pages were created at wiki/user/username.

**Comment by MystK** [comment]
The bot would have to go to  /wiki/userhistory/user/[username], find and access the revisions pre and post DB3, subtract the older delta count from the new delta count, then add it in the JSON data in the hidden params of the latest wiki.

**Comment by AHarman** [comment]
Forgive me for asking a potentially silly question, but is there a particular reason why you would want to look through the revisions? Were deltas removed from wiki pages at any point? Was the switch between the wiki pages done along with the switch to a new version of deltabot?

**Comment by MystK** [comment]
Hey there, not a stupid question at all. Let me try to summarize as best I can.

State of the Application
- Post DB3: There is a database in every user's delta wiki page. This database is what allows DB3 to track the amount of deltas awarded, etc...
- Pre DB3: There is no database, just rendered text and a number showing delta count

When awarding a delta
- Post DB3: DB3 adds a delta with metadata(awarded by, time, CMV title, links) into the database, and uses that to generate a table, update the user's flair, and update the total delta count on the wiki
- Pre DB3: DB3 appends rendered text at the bottom of the wiki page and parses for `{NUMBERHERE} deltas`, and ups the count of NUMBERHERE

The problem
During the introduction of DB3, DB3 also added the database to the wiki page. DB3 didn't just copy parse for the `{NUMBERHERE} deltas`, though. It looked at all the delta links on the wiki page and used the total as the delta count. This means "undocumented deltas," deltas which were added to the total delta count but not the wiki, were not counted. To solve it, we have to grab the NUMBERHERE from the previous wiki page.

Hopefully I explained it well. I know it's a big wall of text and please ask questions if something doesn't make sense!!!

**Comment by Pluckerpluck** [comment]
I have read everything here and I still have no idea what's happening.

Can someone tell me step by step what has happened:

1. You used to store text with links to deltas (or posts or something) at /wiki/userhistory/user/[username]
2. The number of deltas on that page did not necessarily match the number of links
3. When DB3 started up it copied the old links to /wiki/user/[username], those losing the extra deltas
4. You've in some way messed with /wiki/userhistory/user/[username] since this which requires revision hunting?


I **think** that you want:

1. Someone to go to a revision of a page (/wiki/userhistory/user/[username]) before DB3 messed with it and determine the original amount of extra deltas (which in theory is just the delta number - number of links).
2. Store that extra number in some way in the new system

Am I missing something that requires me to do comparisons between revisions which has been implied above?

If it's what I'm thinking this is something I can do.

**Comment by AHarman** [comment]
The only other thing I've seen so far is that there's a "hidden" JSON in the wiki page that presumably needs to be changed as well.

**Comment by Pluckerpluck** [comment]
The JSON thing is part of "store it some way in the new system". Just don't know how they want it done.

**Comment by Snorrrlax** [comment]
I think you're right Plukerpluck, but I don't know enough to answer for sure. Hopefully MystK can clear things up soon.

**Comment by Snorrrlax** [comment]
Ah, again I can't really answer most of this, but I forgot about something that probably explains the changing between formats: at some point [MARS](https://github.com/PixelOrange/MARS) completely stopped working, PixelOrange couldn't help anymore, nobody was continuing his code, and so in order for deltas to be awarded at all we had to revert to [version 1](https://github.com/alexames/DeltaBot) for a while, which was messy.

**Comment by AHarman** [comment]
Ah, I see. I'll start putting something together this evening based on this plan if neither yourself or MystK have any corrections. I'll read from the CMV wiki and write to a wiki on my own sub just to make sure it'll work without breaking the actual wiki.

**Comment by MystK** [comment]
Hey @AHarman, there are some missing information that would change the proposed plan. Let me clarify exactly what happened and what needs to be done.

# Clarifications
- /r/ChangeMyView/wiki/user/USERNAME is the new link
- /r/ChangeMyView/wiki/userhistory/user/USERNAME is the old link

# How DB3 creates the hidden parameters
When DB3 first touches the wiki, it converts the old format to the new format, looking at both the NEW and OLD links.

1.  Delta is awarded, now update the wiki
2. Go to /r/ChangeMyView/wiki/user/USERNAME and parse for all delta comments
3. IF `Any delta history before February 2015 can be found at: /r/ChangeMyView/wiki/userhistory/user/USERNAME` is found, parse for delta comments there also.
4. With the parsed list of delta comments, create a hidden database with data to be used to render a markdown table.
5. Render a table and put the hidden database into the wiki for archiving. All found delta comments from the old and new links have now been compiled into one page.

# The problem
Not all deltas awarded were put into the wiki
- Some links were of the CMV listing itself and not the delta comment. These were not counted
![image](https://cloud.githubusercontent.com/assets/7399140/18960622/351070e4-861f-11e6-96ab-9b6cf9c1512c.png)
- Some deltas were not added to the wiki and the total delta count was just bumped.
![image](https://cloud.githubusercontent.com/assets/7399140/18960666/6b266562-861f-11e6-9f88-18890fb6121b.png)

# The solution
1. Track the revision[If it's not the latest] that DB3 has not yet touched in the new link. Use that delta count as the supposedly correct delta count.
2. If DB3 has touched the wiki, go to when DB3 first touched it[The next revision from step 1] and calculate how many deltas were lost. EX: 10 deltas in step 1, but now 5 deltas. We need to have 5 deltas to the latest wiki. If DB3 has not touched the wiki, move to the next user[wait for DB3 to parse, then the script will be ran again on a daily/weekly schedule].
3. Create the hidden database and append it to the database. For each missing delta added, the below should be appended to the JSON database.

```
{
  "b": "",
  "dc": "",
  "t": "This entry tracks a manually added delta",
  "ab": "",
  "uu": 1
}
```
[An example is in amablue's latest wiki.](https://www.reddit.com/r/ChangeMyView/wiki/user/amablue) When DB3 awards amablue a delta, it will render the table and update the flair with the missing deltas.

Hopefully I explained it well. Please ask if you any questions!

**Comment by Pluckerpluck** [comment]
What about the stuff on /wiki/USERNAME?

And those hidden parameter creation is first time only right? For if it hasn't been dealt with?

How would we deal with stuff you haven't already touched for example?

**Comment by MystK** [comment]
I believe all the stuff in /wiki/USERNAME was moved to one of the new links.
EX: https://www.reddit.com/r/ChangeMyView/wiki/amablue

Correct, the creation of the hidden parameters only happen once. After the first time, data is just added to the hidden parameters.

What do you mean by stuff DB3 hasn't touched?

**Comment by Pluckerpluck** [comment]
Stuff like:

https://www.reddit.com/r/changemyview/wiki/user/40ft

New link, old style. No secret metadata yet. Should this script create the metadata? Stuff like that.

That guy doesn't seem to have a `/40ft` or a `/userhistory/user/40ft` either

**Comment by MystK** [comment]
Not required unless you're willing to go the extra mile. When 40ft receives a delta award by DB3. When DB3 sees that it hasn't been converted, it will convert it.

**Comment by Pluckerpluck** [comment]
Only reason we asked is because right now we can guarantee that no fixes have been tried. We know exactly what's missing. If an old person gets a delta I'm guessing they will face the same problem currently as all the rest are - some deltas may be missed. If you have changed it then there's a chance this problem effects some but not all people, which makes this script much more complex (you now need to know what's been dealt with).

Just bringing this up because it's fairly important.

**Comment by MystK** [comment]
You brought up a good point that has not been addressed by the solution in my above comment. In between step 2 and 3, we need to compare the "to be added deltas" with the "already added deltas" and only add `"to be added deltas" - "already added deltas"` deltas if greater than 0.

With that simple step, the case is handled. ;)

**Comment by Snorrrlax** [comment]
@AHarman @Pluckerpluck

Hey guys, have either of you been able to take a further look at this?

**Comment by Pluckerpluck** [comment]
I assumed AHarman was doing something.... because he said he was gonna throw something together. If he's not I should be able to do something in the next few days.

**Comment by Snorrrlax** [comment]
Since we haven't heard from @AHarman, would you be able to take this on @Pluckerpluck?

**Comment by Snorrrlax** [comment]
Is it possible to insert the missing deltas into the user wiki page as well (by date), rather than just adding them to the delta-count?

**Comment by MystK** [comment]
Yes we can add them by date(if someone wants to do it manually)

**Comment by Snorrrlax** [comment]
Is there a way to do this with code?
