### ISSUE TITLE
Denies and awards delta in the same comment

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#39]
See here: https://www.reddit.com/r/changemyview/comments/54wkyr/cmv_the_us_is_not_free_the_world_is_too_far_gone/d85rlvl?context=3

> This delta has been rejected. The length of your comment suggests that you haven't explained how /u/Amp1497 changed your view (comment rule 4).
>
> In the future, DeltaBot will be able to rescan edited comments. In the mean time, please repost a new comment with the required explanation so that DeltaBot can see it.
>
> Confirmed: 1 delta awarded to /u/Amp1497. [History]
>
> [The Delta System Explained] ​

As you can see in the [user wiki page](https://www.reddit.com/r/changemyview/wiki/user/amp1497), it was definitely awarded.

**Comment by MystK** [comment]
That's definitely some wild stuff going on there. Thanks for catching that.

**Comment by MystK** [comment]
archiving deltaComment below

```
This delta has been rejected. The length of your comment suggests that you haven't explained how /u/Amp1497 changed your view (comment rule 4).

In the future, DeltaBot will be able to rescan edited comments. In the mean time, please repost a new comment with the required explanation so that DeltaBot can see it.

Confirmed: 1 delta awarded to /u/Amp1497. ^[[History](/r/changemyview/wiki/user/Amp1497)]

^[[The Delta System Explained](https://www.reddit.com/r/changemyview/wiki/deltasystem)]
[​](HTTP://DB3PARAMSSTART
{
  "comment": "This is hidden text for DB3 to parse. Please contact the author of DB3 if you see this",
  "issues": {
    "littleText": 1
  },
  "parentUserName": "Amp1497"
}
DB3PARAMSEND)
```

**Comment by Snorrrlax** [comment]
Another example just 15 minutes ago: https://www.reddit.com/r/changemyview/comments/552r5k/cmv_if_you_enjoy_happy_tree_friends_you_are/d87btps

**Comment by MystK** [comment]
fixed. introduced in #27

**Comment by MystK** [comment]
For those comments, we can use the DB3 "delete" command
