### ISSUE TITLE
Should DeltaBot have restarted the sidebar monthly Deltaboard by now? 

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#40]
It's still September on the sidebar? 

The monthly one in the Deltaboard wiki has changed.

**Comment by MystK** [comment]
Investigating right now

**Comment by MystK** [comment]
fixed due to https://github.com/MystK/delta-bot-three/commit/11ec68b3139402b87308e47bd2bf4fb55b3b81a1
