### ISSUE TITLE
Testing mode

### ISSUE THREAD

**Issue by roastchicken** [MystK/delta-bot-three#41]
Currently there are hard-coded strings in the code checking to see if the author is `mystk` to circumvent tests for giving yourself a delta. I think there is better way of doing this, instead of requiring people to replace these occurrences with their own username.

Two possible ways of handling this that I've though of so far:
- Add a new key to credentials.json: `"testingUsername": "myUsernameToUseForTesting"`
- Add some way to use 'testing mode' where checks for authorship are not made

The downside to the `testingUsername` approach is that this may not be wanted in production. I guess it could be set to a blank string or something like that to disable it.

The downside to the testing mode is that the author check may be a check that fails when the code is changed, and if testing mode is enabled then this bug may not be noticed until it is put into production.

Feel free to critique these ideas and/or suggest other ways of handling this.

**Comment by MystK** [comment]
Hey there. I'd like to expand on the second idea. I think it's good to have a --bypass checks parameter when starting DB3.

Get Outlook for iOS




On Sat, Oct 1, 2016 at 9:43 AM -0700, "Julian Montague" <notifications@github.com> wrote:





Currently there are hard-coded strings in the code checking to see if the author is `mystk` to circumvent tests for giving yourself a delta. I think there is better way of doing this, instead of requiring people to replace these occurrences with their own username.

Two possible ways of handling this that I've though of so far:

- Add a new key to credentials.json: `"testingUsername": "myUsernameToUseForTesting"`
- Add some way to use 'testing mode' where checks for authorship are not made

The downside to the testing mode is that the author check may be a check that fails when the code is changed, and if testing mode is enabled then this bug may not be noticed until it is put into production.

Feel free to critique these ideas and/or suggest other ways of handling this.

--
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/MystK/delta-bot-three/issues/41

**Comment by roastchicken** [comment]
Can you pass command-line parameters to node apps?

**Comment by MystK** [comment]
Correct.

Here's a snippet of code I wrote for work [not sure how legal this is] that takes arguments.
````
const abbrev = require('abbrev')
const argv = require('yargs').argv
const longOpts = abbrev('france', 'us', 'italy', 'environment')
const parsedArgv = {}
const opts = _.keys(argv)
for (const opt of opts) {
  if (opt in longOpts) parsedArgv[longOpts[opt]] = argv[opt]
  else parsedArgv[opt] = argv[opt]
}
````

basically, it allows us to type. `-I --it --ita --ital. --Italy` to all mean `Italy`
To pass arguments into the npm script, you type `npm start -- --Italy`

**Comment by roastchicken** [comment]
Maybe don't post snippets from work if you don't know the legality of it 😲. Don't want you getting fired!

I'm sure I can find some information online about passing arguments to node.

**Comment by roastchicken** [comment]
I've done some research on the subject, and there are two ways we could do this:

- The simple, library-free way:
  - We could just check the value of `process.argv[2]`.
  - Pros: doesn't require a library which I think would unnecessarily bloat the project just to add one argument.
  - Cons: Would get unwieldy if we decide to add more arguments, in which case we would want to switch to using a library.
- The advanced, library way:
  - Pros: easily extendable if we want to add more arguments.
  - Cons: slightly more work than the library free way, and doesn't confer much benefit when we only have one argument.

**Comment by MystK** [comment]
No preference on my side, although I feel like it should be more than 1 argument.

Let's assume a new person contributes and seeing this "testing" mode. What does it mean? What is it testing? Is it testing the deltaboards, the comments, the Reddit API rate limiter? 

I think best case scenario, the arguments should be very descriptive.

````
--bypass comment-check
--bypass delta-board-difference-check
--skip comment-checking
--skip delta-board-check
--skip wiki-update
````

I think the above is the best case scenario, but I think a beginning "test" mode which just means "bypassing comment check" would be great since anything really is better than the current solution. ;)

**Comment by roastchicken** [comment]
In your example, would `--bypass` and `--skip` just be aliases or would they have different functionality?

**Comment by MystK** [comment]
Hmm, thinking about it, they seem that they could be the same. Some other parameters I could think about though are

````
--override-delta-boards-subreddit changemyview
--always-update-deltaboards true
````

**Comment by roastchicken** [comment]
Ok. I think with this many parameters it would be a good idea to use a library. I'll take a look at the different options later today and figure out which one works the best for our application.

**Comment by hacksoncode** [comment]
Since adding libraries came up...

Just wanted to add a reminder (also applicable to #38 where an rdbms was
suggested) that the bot is running on an inexpensive 128mb virtual RAMnode
server that has already experienced some problems with running out of
memory.

While, personally, I don't mind too much springing for a more expensive
instance if it's needed (though for whatever reason it looks like RAMnode
doesn't let you *upgrade* this server level, so it would require a
reinstall), we should keep in mind that this is a volunteer hobby, and not
all potential community users of the bot will be similarly cavalier.

IMNSHO, a for loop over argv isn't rocket science, especially since we're
talking about debug settings rather than something that needs to be robust
against end user mayhem.
-- 
Ray

**Comment by MystK** [comment]
Great point. The VM has so little memory I couldn’t do a `npm install` on it. I had to do it on my machine then copy it over.

**Comment by roastchicken** [comment]
128MB RAM? Yeah, the less libraries the better then I guess.

**Comment by roastchicken** [comment]
Since @wyantb has taken initiative and added a command line argument, how do we want to structure the rest of the arguments? Should they all follow the same format as `--debug` (check if string is present in args table and set a const respectively), or do we want to use loop? Or maybe something else entirely?

**Comment by MystK** [comment]
Up to you, to be honest. Doesn't matter to me. As long as the approach you make doesn't affect the --debug flag. ;)

**Comment by wyantb** [comment]
Pretty trivial to add one-off flags for disabling individual rules like `--skip-length-check`, `--skip-parent-check`, etc, in server.js.  That's, what, 3-5 flags for the BAILOUT cases in that file?  Not much bloat in the grand scheme of things.

**Comment by MystK** [comment]
Thought on this @roastchicken, were you still interested in adding a testing mode, or the firefox profiles are a good alternative?

For me I use Chrome and Chrome private mode now.

**Comment by roastchicken** [comment]
I'm not sure I understand how the profiles alleviate the need for a testing mode. The way I understand it, @wyantb is suggesting using multiple reddit accounts to make the comments so that the parent check isn't triggered. That sounds like a lot of work just for one testing comment, definitely something I'd want to do each time I tested the bot.

I'll work on adding a testing mode today.

**Comment by Snorrrlax** [comment]
No objections from me. @MystK?

**Comment by MystK** [comment]
Yes no issues from me. If you’re willing to add a testing mode, I think it’s a great idea.

**Comment by roastchicken** [comment]
Sorry for the long wait. I'll try to add testing mode this weekend.

I'm curious about the purpose of `!parentID.match(/^t1_/g) on line 355 in [server.js](https://github.com/MystK/delta-bot-three/blob/d443ea901554a699ca03a4a242cccf748452f81d/server.js#L355). Is t1 a special prefix that reddit uses?

**Comment by MystK** [comment]
Yes, it's related to the Reddit API. It's used to check if the delta comment is replying to a Comment or the Listing.

**Comment by roastchicken** [comment]
I'm having trouble passing command line arguments to DeltaBot. Has anyone else had success with this? @MystK and @wyantb, I imagine you two have the most experience with this.

According to `npm -h start` and `npm help run-script`, the correct way to pass arguments to a node package is `npm start -- <args>'. An example is given by `npm help run-script`: `npm run test -- --grep="pattern"`. However when I try to run `npm start -- --debug` I get the following message:

`> delta-bot-three@3.2.4 start /home/deltabot/delta-bot-three
> supervisor -w ./lib/server.js ./lib/server.js "--debug"


Node Supervisor is used to restart programs when they crash.
It can also be used to restart programs when a *.js file changes.

Usage:
  supervisor [options] <program>
  supervisor [options] -- <program> [args ...]

Required:
  <program>
    The program to run.

Options:
  -w|--watch <watchItems>
    A comma-delimited list of folders or js files to watch for changes.
    When a change to a js file occurs, reload the program
    Default is '.'

  -i|--ignore <ignoreItems>
    A comma-delimited list of folders to ignore for changes.
    No default

  -p|--poll-interval <milliseconds>
    How often to poll watched files for changes.
    Defaults to Node default.

  -e|--extensions <extensions>
    Specific file extensions to watch in addition to defaults.
    Used when --watch option includes folders
    Default is 'node,js'

  -x|--exec <executable>
    The executable that runs the specified program.
    Default is 'node'

  --debug
    Start node with --debug flag.

  --debug-brk[=port]
    Start node with --debug-brk[=port] flag.

  --harmony
    Start node with --harmony flag.

  -n|--no-restart-on error|exit
    Don't automatically restart the supervised program if it ends.
    Supervisor will wait for a change in the source files.
    If "error", an exit code of 0 will still restart.
    If "exit", no restart regardless of exit code.

  -t|--non-interactive
    Dissable interactive capacity
    With this option, supervisor won't listen to stdin

  -k|--instant-kill
    Dissable interactive capacity
    With this option, supervisor won't listen to stdin

  --force-watch
    Use fs.watch instead of fs.watchFile.
    This may be useful if you see a high cpu load on a windows machine.

  -h|--help|-?
    Display these usage instructions.

  -q|--quiet
    Suppress DEBUG messages

  -V|--verbose
    Show extra DEBUG messages

Options available after start:
rs - restart process.
     Useful for restarting supervisor eaven if no file has changed.

Examples:
  supervisor myapp.js
  supervisor myapp.coffee
  supervisor -w scripts -e myext -x myrunner myapp
  supervisor -- server.js -h host -p port`

This same message is given if `npm run start` or `npm run-script start` is used instead. It also seems to happen regardless of the argument(s) supplied.

I don't know anything about Supervisor, but it seems to me like all of the arguments are being passed to it. Supervisor doesn't know how to react because it treats these as arguments to itself instead of arguments meant to be passed on to the node package.

**Comment by MystK** [comment]
I think you might have to add a -- to the supervisor.

The command I think that works would be `supervisor -w ./lib/server.js ./lib/server.js  -- ./lib.server.js --debug`

**Comment by roastchicken** [comment]
From looking at the documentation of supervisor, I gather that the second instance of `./lib/server.js` is meant to run that file? If so, then I think it would just be `supervisor -w ./lib/server.js -- ./lib.server.js --debug` because the `program` part of the command is just moved according to the documentation ('supervisor [options] -- <program> [args ...]'). Does this seem correct @MystK?

**Comment by MystK** [comment]
Yes you're right ;)

**Comment by roastchicken** [comment]
Ok, I changed the start script in package.json to `supervisor -w ./lib/server.js -- ./lib/server.js` and the --debug argument works. My --bypass-op-check argument isn't working, but I suspect that's due to an error in my code. I'll make a pull request with the changed start script.

**Comment by roastchicken** [comment]
Pull request #72 made regarding the changed start script.

**Comment by MystK** [comment]
Yes, this is related to the Reddit API

**Comment by Snorrrlax** [comment]
Seems the disappearing email responses you mentioned before have come through now!

**Comment by roastchicken** [comment]
Added ability to bypass the check to make sure the delta isn't being given to OP in #76.
