### ISSUE TITLE
Deltaboard Ordering

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#43]
What's the current ordering process when it comes to two users with the same delta score?

Say someone has the top delta score, and then the second place user matches them, the one in second place should stay there rather than take first place.

**Comment by MystK** [comment]
Yes, I believe it is correctly ordered by date.

**Comment by Snorrrlax** [comment]
If you look at the [deltaboards wiki page](https://www.reddit.com/r/changemyview/wiki/deltaboards) you'll see /u/YossarianWWII earned a delta today, which put them rank 2 in the weekly deltaboard (ahead of those who earned one yesterday), which to me suggests this isn't ordered by date?

**Comment by MystK** [comment]
Fixed and good catch. ;) I thought I had handled it correctly.
