### ISSUE TITLE
User with Incorrect Delta Count

### ISSUE THREAD

**Issue by JohnnyO** [MystK/delta-bot-three#47]
A user messaged the mod team today noting that his delta count had been reset.  I know this is likely linked to the existing work on #33 and #35, but I wanted to make sure we listed it here so someone could look into it once the bugs are resolved.

https://www.reddit.com/r/changemyview/wiki/revisions/user/carasci

**Comment by roastchicken** [comment]
It looks like their wiki page was cleared [over a year ago](https://www.reddit.com/r/changemyview/wiki/user/carasci?v=07e58e12-b0d6-11e4-aa2c-22000b690689&v2=78bb8f10-a3f2-11e4-a9c6-22000b6a00e7). I'm not sure this is something related to DeltaBot 3.

**Comment by JohnnyO** [comment]
I believe that clearing was done during the transition from DeltaBot 1 to DeltaBot 2.  It looks like DeltaBot 2 never awarded them anything....

**Comment by MystK** [comment]
Approval from @Snorrrlax to add 37 undocumented deltas? When done right, 10 deltas will be documented but 27 will remain undocumented.

**Comment by Snorrrlax** [comment]
Yeah :)
