### ISSUE TITLE
Switch to pretranspiling?

### ISSUE THREAD

**Issue by ansballard** [MystK/delta-bot-three#49]
Just jumping in via a post in r/node, is there a reason for transpiling at runtime vs transpiling and running the built js? I would think the latter option would remove at least some server overhead. Thoughts?

**Comment by MystK** [comment]
Howdy, no real reason other than ease of deployment. With runtime transpiling, all I need to do is a “git pull” and auto restart. 

 

I’d totally accept a PR if we could include a build step that doesn’t detract from ease of deployment. Maybe just a “git pull,” “npm run build” then “npm start”

**Comment by ansballard** [comment]
Sounds good, I'll throw together a build script in the next day or two.

**Comment by Snorrrlax** [comment]
@ansballard hi, any update on this?

**Comment by ansballard** [comment]
Sorry about that, work got a little wild since my last comment. Here's what I'm planning on testing next time I get a chance (this weekend or bust). Since just using babel would be a bit of a pain since there isn't a dedicated `src/` directory, [browserify](http://browserify.org) allows for keeping the current file structure and bundling to a single file in, for example, a new `lib/` directory. And a matching watch script will mean development should be as easy as before, just with an additional console running in the background.

```bash
# dependencies: npm install --save-dev browserify watchify babelify
browserify ./server.js -t babelify --node --no-bundle-external -o ./lib/server.js # npm run build
watchify ./server.js -t babelify --node --no-bundle-external -o ./lib/server.js # npm run watch
```

**Comment by Snorrrlax** [comment]
Okay great, thank you!
