### ISSUE TITLE
Set up Jenkins for development to production workflow

### ISSUE THREAD

**Issue by MystK** [MystK/delta-bot-three#52]

**Comment by wyantb** [comment]
Any particular reason you say Jenkins?  I use that at work as well, but Travis also seemed to be trivial to setup.  (e.g. https://travis-ci.org/wyantb/delta-bot-three/builds/166862738 showed a failure which I could fix in https://travis-ci.org/wyantb/delta-bot-three/builds/166863356 ).  They seem to have a variety of choices for uploading files, too, in https://docs.travis-ci.com/user/uploading-artifacts/ .  I hadn't used before, but it's based on github webhooks ( https://travis-ci.org/getting_started ).  By default, they run "npm test", which I previously had run eslint and could be adapted for #53 as well of course

**Comment by MystK** [comment]
Nope, just what I'm familiar with. I should change this to CI and CD wanted.
