### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by MystK** [MystK/delta-bot-three#53]
Discussion tag to talk about how we want to implement unit tests

**Comment by stedop** [comment]
There seems to be a few packages out there for unit testing, I haven't used any of them for node so whichever one we go with the learning curve will be the same.

One of the issues with unit tests is not to be spamming the sub so I think we will need a test sub (if there isn't already one) and a test bot acount or we will need a build of reddit on what ever dev envrionment (which obviously will be fun to setup).

I think a test sub will be easier, and open to everyone but a full reddit build will be more robust.

**Comment by MystK** [comment]
Howdy. I think we might be referring to different things. For me, a unit test is testing a single function of the code. Ex: extract the "create deltaboards" function. If we give it a set of inputs, we expect a set of outputs.

I think you're referring to end to end testing(e2e), which, like you said, would be pretty fun to set up. I will open up another issue for that. It would be great if we could run these e2e tests with every PR.

Honestly, I am not an expert with testing. Any and all help would be appreciated! The buzz words that I know for unit and e2e tests are karma, chai, mocha, gulp, phantomjs.

Get Outlook for iOS<https://aka.ms/o0ukef>

_____________________________

**Comment by stedop** [comment]
No, sorry I didn't explain myself well I meant, Unit test frameworks
instead of using nodes built in assert functions.

I was thinking with unit tests  there are going to be some functions that
require contact with reddit so either we would need to set up dummy json
calls (which can be a pain without a good framework) or test with a test
sub.

**Comment by thomas-alrek** [comment]
I personally really like Chai, it's very easy to use

**Comment by ansballard** [comment]
I'll throw in a vote for ava. Built to be async, use es6/7, and at least for me pretty easy to visually parse.

**Comment by Snorrrlax** [comment]
@thomas-alrek hi, are you able to help us at all with any of the issues here?
