### ISSUE TITLE
DB no longer "tags" the user with /u/

### ISSUE THREAD

**Issue by hacksoncode** [MystK/delta-bot-three#60]
A user just complained about the way that DB's new delta format no longer "tags" the user with "/u/" (which conveniently gets automatically converted into a link that someone can click on for their user page).

I think it's a fair cop. At the very least, the messages are now inconsistent, because the "too short" message still adds the /u/.

**Comment by MystK** [comment]
?In the delta comment?

**Comment by hacksoncode** [comment]
I'm impressed at the speed of your response... yes, in the delta comment. Sorry... I was writing a full description when I accidentally hit enter and it posted the damn bug... silly interface.

**Comment by MystK** [comment]
Gonna ping @Snorrrlax here because he requested to change the delta comment.

**Comment by hacksoncode** [comment]
Yeah, it does need discussion for sure.

**Comment by Snorrrlax** [comment]
Yeah, I think the reason I left it out this time is so it would look "cleaner" with only one link, especially because they would be right next to each other:

> Confirmed: 1 delta awarded to [/u/hacksoncode](http://www.reddit.com/u/Hacksoncode). ([100&#8710;](http://www.reddit.com/r/changemyview/wiki/user/Hacksoncode))

**Comment by Snorrrlax** [comment]
But to be honest that's not a great reason so I'm not bothered if you want to add it back.

**Comment by hacksoncode** [comment]
They're two different links, though. The delta link is to the user's *delta wiki page*, but the /u/ link is to the user's *comment history* page. 

Also, people get a notification when their user link is mentioned, but not if it's just their username. The way it is now, the only way someone knows they got a delta is if they happen to look. 

I think it's moderately important, personally.

**Comment by Snorrrlax** [comment]
Yeah fair enough, I'm happy with that.

**Comment by roastchicken** [comment]
I'm working on changing this right now. Will update with progress.

**Comment by roastchicken** [comment]
I'm 99% sure that reddit will automatically make /u/username link to https://www.reddit.com/u/username/, but I don't want to make false assumptions. Can someone confirm this?

**Comment by hacksoncode** [comment]
It does do the conversion automatically when you type it in to a comment, but I'm not sure about when a comment is added via the API.

**Comment by MystK** [comment]
Yes you are correct!

**Comment by roastchicken** [comment]
Hi, sorry for the wait. I forgot about this after changing the file this afternoon. For some reason Pageant (my key manager) is crashing whenever I try to add a key, so I'm not sure I'll be able to create a pull request tonight. It's pretty simple, just add '/u/' before the first occurance of 'USERNAME' on line 3 of i18n.json.

edit: While I was writing this I opened Pageant a third time and it worked. Going to test now and then I'll make a pull request if all is in order.

**Comment by roastchicken** [comment]
So I tried overriding the self-delta check by just replacing all occurrences of 'mystk' with 'roastchickenn' (my Reddit username I'm using for testing) but it doesn't seem to be working. Not sure how to test this, I guess I'll take a second look at the self-delta check but I don't see any changes to this code since last time that would make this fail.

**Comment by hacksoncode** [comment]
Throw me a link to the comment and I'm happy to send you a test delta.

**Comment by roastchicken** [comment]
Thanks for the offer but it's all cleared up now. I would be happy to send you a link and have a second person test it out, but I'm getting off for the night and I've already shut down the bot. If we want to double check I can throw it up tomorrow morning and leave it running throughout the day for anyone to test.
