### ISSUE TITLE
requires wrapped in try blocks don't mesh with browserify

### ISSUE THREAD

**Issue by ansballard** [MystK/delta-bot-three#63]
So if we move away from runtime transpiling, catching failed requires aren't going to work. Example: https://github.com/MystK/delta-bot-three/blob/master/server.js#L43. It's also a little weird to be mixing import/export statements with requires, so it's probably best to replace them anyway. It should be relatively easy to swap them out for fs.readFileSync() and JSON.parse(), but I figured a separate issue should probably go in beforehand.

**Comment by MystK** [comment]
browserify on the server side? Interesting, could you elaborate on what you were thinking about doing?

For the imports and requires, they need to be mixed because they work different. Requires are not hoisted to the top but imports are.

**Comment by MystK** [comment]
Overall, if it requires removing the runtime requires to enable compile time transpilation, I'm cool with that.

**Comment by ansballard** [comment]
There are actually a few flags in browserify (--node and --no-external-builtins) that allow it to export a single bundled file runnable in node, and it's worked well enough for me in other projects. Since the source files aren't in their own subdirectory, it seemed like it would be a little cleaner to just specify an entry file, rather than the root directory and a bunch of files to ignore.

Agreed, those cases can't be switched to import/export, but they could be switched to fs.readFileSync, which seems a little more semantic, and can be handled before runtime.

**Comment by MystK** [comment]
Cool. I wasn't even aware that browserify could be used on the server side. I'm glad you opened up an issue and I'm looking forward to your PR! 👍
