### ISSUE TITLE
This delta wasn't recognised

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#66]
A user messaged us about this delta that hadn't been added by DeltaBot: https://www.reddit.com/r/changemyview/comments/5870ge/cmv_i_think_democracy_is_bad_method_to_elect/d8xz9je

We sent a PM to DeltaBot and it scanned and awarded the delta. 

Any idea why it wasn't awarded at first? There's no edit asterisk.

**Comment by hacksoncode** [comment]
I'm guessing it was edited in shortly after posting it. DB is really fast these days, often getting to a comment mere seconds after posting, and almost never more than 30 seconds. 

By contrast, the edit asterisk doesn't appear until you do an edit more than 3 minutes after posting.

**Comment by MystK** [comment]
Yes. Hacks on code is right. DB3 is ninja fast. That is most likely what happened.

Some news on edited. I will very soon have free time to work on it!

Get Outlook for iOS<https://aka.ms/o0ukef>




On Tue, Oct 18, 2016 at 8:39 PM -0700, "hacksoncode" <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm guessing it was edited in shortly after posting it. DB is really fast these days, often getting to a comment mere seconds after posting, and almost never more than 30 seconds.

By contrast, the edit asterisk doesn't appear until you do an edit more than 3 minutes after posting.

-

**Comment by Snorrrlax** [comment]
Ah this makes sense. Cheers!
