### ISSUE TITLE
My DeltaCount has been Erased

### ISSUE THREAD

**Issue by JohnnyO** [MystK/delta-bot-three#68]
Oh No!

My delta count no longer appears next to my user name.  Not sure when this first started appearing, but I currently have nothing appearing next to my username when I post.  I don't think this is the same as the issue effecting other users, like #35, as I have been correctly receiving deltas from DeltaBot3 over the last couple of weeks, and my user page looks OK.  Also, it appears that the problem here is just that my flair has been deleted.  I can add it back, but I'm afraid that will mess up the bot.

Maybe its a weird bug because I'm also a mod?  Not sure.

Anyone have any idea what is going on?

Wiki Link:  https://www.reddit.com/r/changemyview/wiki/user/cacheflow
Recent Postings:  https://www.reddit.com/user/cacheflow

**Comment by MystK** [comment]
Hmm. definitely interesting! Please please add it back manually. It shouldn't affect DB3. If it happens again can you comment here? Will leave open.

**Comment by JohnnyO** [comment]
Never mind.  This was completely user error.  Apparently, at some point, the checkbox for "show my flair" had gotten disabled on my account.  Not sure how that happened, but it was completely on my end.
