### ISSUE TITLE
Cluttered build instructions

### ISSUE THREAD

**Issue by roastchicken** [MystK/delta-bot-three#69]
This is a bit nitpicky, but I feel like we're trying to put too much into the build instructions. It currently contains information about:
- Building DeltaBot
- Setting up a testing subreddit and bot
- Commit and pull request guidelines

I feel like each of these things should be split off into a separate section.

Also, only slightly related but, I think the building part of the build instruction miss the important step of `npm install`. I'm not 100% if this is just something that happens on Windows, but I just tried building DeltaBot on my computer and I got an error about 'supervisor' which seems to be another package that needed to be installed. After running 'npm install' this error went away (and another appeared, but that's another issue entirely).

Let me know your thoughts; I would make a pull request but I want to make sure this is something people agree with and not just me being overparticular.

**Comment by MystK** [comment]
I think you're right that the contributing should be split up. I think there should be a "How to build from scratch" and "Shorthand version." I'd like anyone, without knowledge of Git or NodeJS be able to follow the full instructions. Thoughts?

**Comment by MystK** [comment]
Also wouldn't mind a PR to add "npm install"

**Comment by roastchicken** [comment]
`npm install` has been added in PR #71.

**Comment by roastchicken** [comment]
@MystK when you say "Shorthand version", what would that include? Would "How to build from scratch" still contain things like commit and pull request guidelines?

**Comment by MystK** [comment]
I think "How to build from scratch" would not contain contributing guidelines.

The shorthand version would be what you are discussing here. Maybe something like "clone the repo, npm i, npm runb uild, npm start" Something short?

**Comment by roastchicken** [comment]
Would the shorthand version contain installing node and npm?

I think it would be logical to move [steps 11 and 12](https://github.com/MystK/delta-bot-three/blob/dca6415eaa19aeaeba65ce9f6aad35dd0b9ae877/README.md)  over to "Contributing". Do you agree @MystK?

**Comment by MystK** [comment]
Yes, I think the shorthand should have a little snippet of "Install the node version in .nvmrc"

Yes to your second question! :)

**Comment by MystK** [comment]
Yes, I think the shorthand version should have something like “Download the Node version in the .nvmrc file”

Agreed that 11 and 12 belong to contributing.

**Comment by roastchicken** [comment]
Is it just me or does anyone else just see two replies from @MystK in a row? Maybe I'm not seeing someone's comment.

**Comment by Snorrrlax** [comment]
MystK mentioned the other day that he replied to some comments via email and they didn't come through. This must be them coming through now.

**Comment by roastchicken** [comment]
That makes a lot of sense. I was beginning to suspect that after I saw comments from wyantb and MystK at the same time on an issue where they both said they had tried to reply with email but it didn't go through.

**Comment by Snorrrlax** [comment]
Yeah I was confused for a minute :P btw you should have received an invite via email for the slack chat, not sure how much use it'll be, but worth trying out. I sent @MystK an invite too.

**Comment by roastchicken** [comment]
Yeah, I saw that. I haven't been able to check it out yet as I've been drowning in school projects.

**Comment by Snorrrlax** [comment]
No rush!
