### ISSUE TITLE
New copy for too short of text

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#7]
When a delta is rejected for having too little text alongside it, this is DeltaBot's response, as we know:

"littleText": "This delta is currently disallowed as your comment contains either no or little text ([comment rule 4](http://www.reddit.com/r/changemyview/wiki/rules#wiki_rule_4)). Please include an explanation for how /u/PARENTUSERNAME changed your view. **If you edit this in, replying to my comment will make me rescan yours**."

The bolded part meant if DeltaBot received a reply, it would trigger a re-scan of the comment in question. However, is it now possible for us to change this text to say "**If you edit this in, your comment will be rescanned**", and DeltaBot will automatically rescan all edited comments as if they are a new comment, without needing a trigger reply? In which case it would delete its previous response and re-comment with a confirmation of a delta award, if the edit met the criteria?

**Comment by MystK** [comment]
Yes, I believe it is possible to rescan edited comments. Can you provide me with the updated copy you would like?

**Comment by Snorrrlax** [comment]
Cool. We'd like it to say this: 

> This delta has been rejected. The length of your comment suggests that you haven't explained how /u/username changed your view (comment rule 4). Please edit your comment and include a short explanation - it will be automatically re-scanned.

Will it be fairly easy for us to change the wording of comments if we want to?

**Comment by MystK** [comment]
Yes, ezpz
