### ISSUE TITLE
Slack Chat

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#73]
Hi,

The mods of /r/changemyview have a [slack](https://slack.com/) channel for discussing mod things. Within this we have a DeltaBot channel that we added MystK to. It's good for quicker discussions.

**Edit**: I've created a separate team for it: https://deltabotdevs.slack.com

Do any others who have been involved here want to be added? If so I'll need an email address. 

Just let me know! @roastchicken @wyantb @ansballard @stedop

**Comment by Snorrrlax** [comment]
@MystK if you'd rather discussions were kept here than I can take this down.

**Comment by roastchicken** [comment]
Sounds interesting, I'd like to be added. Do you know if I need to use the same email address that I've used with Slack before? If not, roast@roastchicken.io is the email I'd like to use.

**Comment by Snorrrlax** [comment]
I've invited you to the CMV slack but I've just realised I can't limit you to one channel, which isn't ideal since you'd get lots of unnecessary notifications. 

What I'll do is start a new team on slack and invite you to that.

**Comment by Snorrrlax** [comment]
deltabotdevs.slack.com

**Comment by Snorrrlax** [comment]
@hacksoncode do you want to join?

**Comment by wyantb** [comment]
If we go for it, I'm wyantb@gmail.com - could be helpful for kind of status updates / quick discussions that aren't ready enough for PRs etc

**Comment by Snorrrlax** [comment]
Cool, I've sent invites to yourself and @roastchicken

**Comment by roastchicken** [comment]
@Snorrrlax since you've already made a separate Slack it's not too important, but I'm 99% sure you can turn off notifications per-channel so being bombarded with notifications isn't an issue.

**Comment by MystK** [comment]
Yes I think slack is good for quick discussions. Before making any changes from slack discussion, I’d like to have a process where we put up some meeting minutes or things we discussed from Slack(if we discuss adding features/etc) onto GitHub for all the decision makers to discuss and leave a paper trail.
