### ISSUE TITLE
User Request for Missing Deltas

### ISSUE THREAD

**Issue by JohnnyO** [MystK/delta-bot-three#74]
User had 4 deltas (under the old, old system)

Recent update awarded them 1 delta.

Now they are showing a total of 1 delta.  Can someone look into this?

Current Page: https://www.reddit.com/r/changemyview/wiki/user/ausiv
Old Deltas: https://www.reddit.com/r/ChangeMyView/wiki/userhistory/user/ausiv

**Comment by hacksoncode** [comment]
Yeah, we're starting to see a lot of these... not sure if it's worth the effort to do any of the things in #33 or #35, but it's getting to be a bit of a hassle. 

I forget... did we at least ever come up with a procedure for adding them manually that a) fixes their delta flair immediately, b) fixes the problem so that it doesn't come back for them, and c) isn't too complicated?

If so, where's the documentation?

**Comment by JohnnyO** [comment]
Here is another user that came in through modmail today

https://www.reddit.com/user/DaSilence

**Comment by Snorrrlax** [comment]
Another user:

https://www.reddit.com/user/siiimo

**Comment by MystK** [comment]
All users have been fixed.

This is what you add.

```
{
      "b": "",
      "dc": "",
      "t": "This entry tracks a manually added delta",
      "ab": "",
      "uu": 1
},
```

Check out the above wiki's "edit" for an example. 

All of their delta counts will be updated on a new delta award.

**Comment by Snorrrlax** [comment]
Thanks. Will there be a way in the future to correct the delta wiki pages as well as their count?

**Comment by MystK** [comment]
The bot will automatically generate and update the delta count/wiki page after a delta award. You could also do it manually, but it would take some time. You would just look at the table and add extra line to the table. Then you would update the delta count.

**Comment by Snorrrlax** [comment]
I might test this by awarding one of these users a delta, and then using the delete command to undo it?

**Comment by MystK** [comment]
Smart. Yes I think that would work, but one of their comments needs to have a delta in it. There is no force add.

**Comment by MystK** [comment]
You could delete then add maybe?

**Comment by Snorrrlax** [comment]
https://www.reddit.com/r/changemyview/comments/5f79kc/cmv_there_was_nothing_special_about_2016_bad/daj47ch/

**Comment by Snorrrlax** [comment]
https://www.reddit.com/r/changemyview/wiki/user/siiimo

**Comment by Snorrrlax** [comment]
Doesn't seem to have worked?

**Comment by Snorrrlax** [comment]
Also, this was the user's comment: "Used to be four. Was just awarded a delta and it's now one."

But DeltaBot only added 1 manually which gives Siiimo a total of 2 (excluding my test one).

**Comment by MystK** [comment]
Good find. The manual deltas I added were removed because they thought it was a duplicate. Could you try again? I think I fixed it. It should work if you delete the comment.

**Comment by MystK** [comment]
Hmm. I see it hasn't been fixed.

**Comment by Snorrrlax** [comment]
Just did it again: https://www.reddit.com/r/changemyview/wiki/user/siiimo

**Comment by MystK** [comment]
Fixed. ;) Thanks for working with me. Let me edit the other wiki pages.

**Comment by Snorrrlax** [comment]
Is there any way to recover the original links of the previous deltas?

**Comment by MystK** [comment]
Unless someone wanted to do it manually, it would be part of the "missing deltas fix" ticket

**Comment by Snorrrlax** [comment]
Ah yes, so is this code you've added set up in a way that makes it easy to replace when the time comes to source all missing deltas?

**Comment by MystK** [comment]
Yup. :) It'll require some extra programing but it should be fairly straightforward.

Below is some code to use to add missing deltas and generate the hidden parameters.

```
deltasToAdd = []
for (var i=1; i <=42; ++i) {
	deltasToAdd.push({
		"b": "https://www.reddit.com/",
		"dc": `${i}`,
		"t": "This entry tracks a manually added delta",
		"ab": "",
		"uu": 1
    })
}
JSON.stringify(deltasToAdd, null, 2)
```

This is an example of adding 42 deltas.

Just put it into your browser console.

![image](https://cloud.githubusercontent.com/assets/7399140/20676808/daf7d844-b545-11e6-9ad6-f1735b092eed.png)

![image](https://cloud.githubusercontent.com/assets/7399140/20676818/e1302df6-b545-11e6-83d9-5b964fe189ae.png)

**Comment by Snorrrlax** [comment]
Okay nice, I'll trust you on this haha!

**Comment by hacksoncode** [comment]
OBTW, if you want to edit the user's displayed delta count without waiting for them to be awarded another delta, you can just edit their flair... like we used to do ages ago.
