### ISSUE TITLE
Weekly Deltaboard Bug?

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#78]
So it's the 1st of November and the monthly deltaboard in the sidebar has been restarted. I had a look at the deltaboards wiki page, [here](https://www.reddit.com/r/changemyview/wiki/deltaboards) and I found the listings a bit strange. Since it might update by the time anyone sees this, [here's a screenshot](http://i.imgur.com/UyyNsv0.jpg). 

As far as I understand it, the daily and monthly deltaboards are correct. If those are the only deltas awarded today, then since it's the first day of the month they should be the only deltas on the monthly board. But it's not the first day of the week, and I'm pretty sure there was some awarded yesterday, but these aren't listed on the weekly board?

**EDIT:** Also, can we change the first day of the week to Monday.

**Comment by MystK** [comment]
Exploring right now. I think it's a quick fix.

**Comment by MystK** [comment]
PR merged. Pending deploy to Dev and then QA approval

**Comment by Snorrrlax** [comment]
Can this issue be closed then?

**Comment by MystK** [comment]
Lets wait until I deploy to dev and you give a thumbs up in case we find regression issues.

**Comment by Snorrrlax** [comment]
Okay no problem.

**Comment by Snorrrlax** [comment]
@sahuk 

Just tested this, but it doesn't seem to be working: https://www.reddit.com/r/changemyviewDB3dev/wiki/deltaboards

Two test deltas awarded, both added to daily and monthly deltaboards, but not added to the weekly deltaboard.

**Comment by sahuk** [comment]
Sad to hear that. I am trying to avoid setting up my own subreddit just to test this. Did it work prior to my commit?

Ideally this code would be in a separate function that could be unit tested. Now it's all a big function that does most logic and I/O.

**Comment by Snorrrlax** [comment]
As far as I'm aware, weekly deltaboard worked in the test subreddit beforehand.

We have a slack chat for this project (which we'd love you to join if you plan on helping here and there some more?), in which @MystK mentioned that the date (for Sunday) you used to compare is wrong?

**Comment by MystK** [comment]
Feel free to use my subreddit. If you PM me on Reddit, I can give you mod access to your account/test account.

**Comment by Snorrrlax** [comment]
The 1st of December will be a Thursday, and a good chance to test this out if the code is written in time?

**Comment by Snorrrlax** [comment]
@sahuk, would you be able to have another look at this?

**Comment by MystK** [comment]
Fixed and deploying today. Please monitor for issues then will close
