### ISSUE TITLE
DeltaBot Stickied Comment

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#86]
The CMV mods have been discussing an idea, inspired by a [suggestion](https://www.reddit.com/r/ideasforcmv/comments/5elt4n/put_a_link_to_every_delta_given_out_by_op_in_a/) from one of our users:

Title: "Put a link to every Delta given out by OP in a stickied comment"

Message: "I think it would be useful to people to know what's already said, so it's not repeated.
DeltaBot would be the poster." (I left out the remainder as I don't agree with it, will clarify below).

The links would include context, yet to be decided, but not unlimited. It would be pointless linking to a thread that had a delta 100 comments down. More than likely we'll truncate this to say 4 comments.

**Edit 1:** Just to be clear, the comment which the delta was awarded to should be linked, not the delta comment itself.

If this still isn't clear just let me know. Thanks!

**Edit 2:** The format of the stickied comment:

---

/u/username (OP) has awarded x deltas to the following comment(s):

* [The first sentence or so of the comment will be pasted here and cut off after x characters...](https://www.reddit.com/r/changemyview/)

* [The first sentence or so of the comment will be pasted here and cut off after x characters...](https://www.reddit.com/r/changemyview/)

[Delta System Explained](https://www.reddit.com/r/changemyview/wiki/deltasystem) | [Deltaboards](https://www.reddit.com/r/changemyview/wiki/deltaboards) *(Superscripted)*

---

If the comment begins with a quote (> symbol), that text should be ignored. The first sentence unquoted should be copied for the link.

**Comment by MystK** [comment]
Hello. Requirements clarification. When you mean context limited to 4 parent comments, do you mean that wherever a delta is, show only 4 parent comments max, or look only 4 comments down from the main comment max?

Also, could you put this into the roadmap with prioritized?

**Comment by Snorrrlax** [comment]
> do you mean that wherever a delta is, show only 4 parent comments max

Yes, 4 parent comments max (can be edited to 5 or 3 or 2 etc. in the future if we decide 4 is wrong).

**Comment by MystK** [comment]
Gotcha, makes sense to me now. Thanks.

**Comment by Snorrrlax** [comment]
> Also, could you put this into the roadmap with prioritized?

Done!

**Comment by Snorrrlax** [comment]
Just to be clear, the comment which was awarded a delta should be linked to, not the OP's delta comment.

**Comment by Snorrrlax** [comment]
We're currently discussing a new take on this issue. I'll close this one and make another later to explain.
