### ISSUE TITLE
Delta-wiki-page table format

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#88]
I just noticed something, the table on user wiki pages uses this format:

    | Date | Submission | Delta Comment | Awarded By |
    | --- | :-: | --- | --- |

Can we change it to follow the format of deltaboards? (I'm not sure if the number of dashes matters):

    | Date | Submission | Delta Comment | Awarded By |
    | :------: | :------: | :------: | :------: |

Thanks!

**Comment by Snorrrlax** [comment]
The code should be updated to this for the creation of new wiki pages, but in dealing with wiki pages that already exist, which would be easier?:

* Update format upon editing a wiki page
* A one-time script that goes through and updates them all

**Comment by MystK** [comment]
Hi @Snorrrlax, can you verify that this is how you want it to look.

I temporarily made the change to this wiki.

https://www.reddit.com/r/changemyview/wiki/user/pepperonifire

If you give a thumbs up, I can make it to DB3 updates ANY wiki board on delta award. So old ones with a new delta will also be updated.

**Comment by Snorrrlax** [comment]
Yes, that's it :)

**Comment by MystK** [comment]
Future wiki updates will now have the new table centering. All old wiki tables will be updated on Delta award.
