### ISSUE TITLE
DeltaBot Stickied Comment (Updated)

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#89]
I closed the last version of this issue as we've changed the idea slightly.

Note: This requires the /r/DeltaLog issue (#17) to be finished first.

Upon OP awarding a delta, we'd like DeltaBot to sticky the following comment:

> /u/username (OP) has awarded X deltas in this post.
>
> A compilation of all deltas awarded in this post (OP and non-OP) can be found [here](link to post), in /r/DeltaLog.
>
> Please note that a change of view [is not necessarily a reversal](https://www.reddit.com/r/changemyview/wiki/index), and that OP awarding a delta doesn't mean the conversation has ended.
>
> [^Delta ^System ^Explained](https://www.reddit.com/r/changemyview/wiki/deltasystem) ^| [^Deltaboards](https://www.reddit.com/r/changemyview/wiki/deltaboards)

**Comment by Snorrrlax** [comment]
@wyantb am I right to assume from reading your comments in #17 that you're dealing with this issue too? I'll add the in progress label if so.

**Comment by MystK** [comment]
Thank you @wyantb! Closing this issue. Any new issues related to this, please open a new issue!
