### ISSUE TITLE
Change first day of the week to Monday

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#97]
Currently the first day of the week (for the weekly deltaboard) is Sunday. Can we change this to Monday please?

**Comment by hacksoncode** [comment]
Obviously it's not a technical challenge... but why do we want to contravene the standard that weeks start on Sunday?

**Comment by hacksoncode** [comment]
Sorry, wrong button.

**Comment by Snorrrlax** [comment]
I think it would be best to use international standards since we are a worldwide forum: https://www.timeanddate.com/calendar/days/

**Comment by hacksoncode** [comment]
Ok, but we start FTF based on US Eastern Time. If we were using UTC, that would make more sense. 

But sure... we could do that if we want... When should Monday start, then, for purposes of counting deltas?

**Comment by Snorrrlax** [comment]
I'll admit there is a slight contradiction here. I want to universally standardise DeltaBot (hence the change to Monday and UTC for Deltaboards), but FTF wouldn't work as well if set in UTC. Since a large amount of our users are American, and FTF would start at 4pm Thursday Eastern Time if scheduled to UTC, I imagine we'd get a lot of complaints.

**Comment by Snorrrlax** [comment]
Since we're changing the Deltaboards to UTC #84, Monday should begin at midnight UTC.

**Comment by MystK** [comment]
Fixed and deploying today. Please monitor for issues then will close
