### ISSUE TITLE
Minor improvement to the "delete" command

### ISSUE THREAD

**Issue by Snorrrlax** [MystK/delta-bot-three#98]
Currently we have AutoMod set up in a way that allows us to deal with reported delta abuse better. AutoMod autofills a PM, like so: https://www.reddit.com/message/compose?to=DeltaBot&subject=delete&message=https://www.reddit.com/r/changemyview/comments/5i9iwe/cmv_rcmv_is_the_best_subreddit/db7emz9/?context=3

The problem is AutoMod adds ?context=3 to the end of a permalink, which is causing DeltaBot to ignore the PMs. Can we change this so added context makes no difference?

**Comment by MystK** [comment]
On initial inspection of the code, it looks like the ?context=3 is handled. Will investigate further later. Bad timing because Reddit is down right now.

**Comment by MystK** [comment]
Added in https://github.com/MystK/delta-bot-three/commit/1035fb482504c9081e5fbff6730d6b8f8e5b3222

will deploy to production today

Will leave open until I get a thumbs up from @Snorrrlax

**Comment by MystK** [comment]
I tested it and it seemed to work. WIll close
